### ISSUE TITLE
remote server returned an error: (400) Bad Request

### ISSUE THREAD

**Issue by ajaydell** [maikvandergaag/msft-extensions#242]
Hi Team,

there is no connectivity issue with my workspace when i am trying add user into that workspace i can able to add but there is a issue when i am trying to upload reports file into my workspace I am getting below error. Please help me to resolve the same.

Error:
020-11-26T06:42:03.2626886Z ##[debug]System.Net.WebException: The remote server returned an error: (400) Bad Request.
2020-11-26T06:42:03.2649207Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
2020-11-26T06:42:03.2671131Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
2020-11-26T06:42:03.3164742Z ##[error]The remote server returned an error: (400) Bad Request.
2020-11-26T06:42:03.3167121Z ##[debug]Processed: ##vso[task.logissue type=error]The remote server returned an error: (400) Bad Request.
2020-11-26T06:42:03.3183261Z ##[debug]Processed: ##vso[task.complete result=Failed]
2020-11-26T06:42:03.4427685Z ##[section]Finishing: Power BI Action: Publish

**Comment by maikvandergaag** [comment]
Please add the system.debug variable and set it to true.

And then send the log.

**Comment by ajaydell** [comment]
2020-11-27T11:26:59.8931268Z ##[debug]Leaving D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\2.0.3\run.ps1.
2020-11-27T11:26:59.9188740Z ##[debug]Caught exception from task script.
2020-11-27T11:26:59.9248807Z ##[debug]Error record:
2020-11-27T11:27:00.3513882Z ##[debug]Invoke-API : The remote server returned an error: (400) Bad Request.
2020-11-27T11:27:00.3516457Z ##[debug]At D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\2.0.3\ps_modules\PowerBi\PowerBi.psm1:450 char:15
2020-11-27T11:27:00.3518781Z ##[debug]+ ...   $result = Invoke-API -Url $url -Method "Post" -AccessToken $AccessT ...
2020-11-27T11:27:00.3520520Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-11-27T11:27:00.3522246Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [Write-Error], WebException
2020-11-27T11:27:00.3524209Z ##[debug]    + FullyQualifiedErrorId : System.Net.WebException,Invoke-API
2020-11-27T11:27:00.3525195Z ##[debug] 
2020-11-27T11:27:00.3526303Z ##[debug]Script stack trace:
2020-11-27T11:27:00.3527534Z ##[debug]at Invoke-API, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\2.0.3\ps_modules\PowerBi\PowerBi.psm1: line 148
2020-11-27T11:27:00.3529229Z ##[debug]at Import-PowerBIFile, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\2.0.3\ps_modules\PowerBi\PowerBi.psm1: line 450
2020-11-27T11:27:00.3530991Z ##[debug]at Publish-PowerBIFile, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\2.0.3\ps_modules\PowerBi\PowerBi.psm1: line 567
2020-11-27T11:27:00.3532857Z ##[debug]at <ScriptBlock>, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\2.0.3\run-task.ps1: line 79
2020-11-27T11:27:00.3534222Z ##[debug]at <ScriptBlock>, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\2.0.3\run.ps1: line 72
2020-11-27T11:27:00.3535309Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-11-27T11:27:00.3536322Z ##[debug]at <ScriptBlock>, <No file>: line 22
2020-11-27T11:27:00.3537091Z ##[debug]at <ScriptBlock>, <No file>: line 18
2020-11-27T11:27:00.3537886Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-11-27T11:27:00.3538618Z ##[debug]Exception:
2020-11-27T11:27:00.3539617Z ##[debug]System.Net.WebException: The remote server returned an error: (400) Bad Request.
2020-11-27T11:27:00.3540653Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
2020-11-27T11:27:00.3541558Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
2020-11-27T11:27:00.3581839Z ##[error]The remote server returned an error: (400) Bad Request.
2020-11-27T11:27:00.3584977Z ##[debug]Processed: ##vso[task.logissue type=error]The remote server returned an error: (400) Bad Request.
2020-11-27T11:27:00.3613523Z ##[debug]Processed: ##vso[task.complete result=Failed]
2020-11-27T11:27:00.3877603Z ##[section]Finishing: Power BI Action: Publish

**Comment by ajaydell** [comment]
we are following this documentation but on this documentation showing 3* version on our it is showing 2* how can we upgrade version on our Azure Devops.
https://community.powerbi.com/t5/Community-Blog/PowerBI-CICD-using-Azure-DevOps/ba-p/769244

Please help me to resolve the same.

**Comment by ajaydell** [comment]
Hi Maik,

I added variable as system.debug = true and added log on above comment please help me to resolve the same

**Comment by maikvandergaag** [comment]
@ajaydell - version is already version 5 if i'm not misaken are you using azure devops online

**Comment by ajaydell** [comment]
Hi Maik,

attached screenshot for reference i am able to see task version 2* only.

![image](https://user-images.githubusercontent.com/33676904/100737942-e1ea4780-33fa-11eb-9bfc-bb5ec76112e1.png)

**Comment by maikvandergaag** [comment]
ok, what kind of resource are you trying to publish and what is your Azure DevOps setup?

**Comment by ajaydell** [comment]
Hi Maik,

i am trying to publish pbix file. Azure DevOps service (URL: dev.azure.com)

**Comment by ajaydell** [comment]
Hi Maik,

How can we upgrade the Power Bi Actions version on extensions. 
On my azure DevOps it was showing version 2* only. please help me to resolve the same.

![image](https://user-images.githubusercontent.com/33676904/100980951-0e71a100-356c-11eb-953a-dbf807853819.png)

**Comment by maikvandergaag** [comment]
You need to install the new version: https://marketplace.visualstudio.com/items?itemName=maikvandergaag.maikvandergaag-power-bi-actions
