### ISSUE TITLE
Operation returned an invalid status code 'Unauthorized'

### ISSUE THREAD

**Issue by rahulraajtanwar** [maikvandergaag/msft-extensions#283]
We are not able to deploy power bi report using AzureDevOps. When we tried to use action "Add a new user to an Workspace" it worked but other actions like "Upload PowerBI Report" are not working and returning the below error.
Error: 
##[error]Operation returned an invalid status code 'Unauthorized'

**Comment by maikvandergaag** [comment]
That is due to not having the correct amount of authorization or misconfiguration

**Comment by rahulraajtanwar** [comment]
But I have configured everything the same as you mentioned and also the action "Add a new user to an Workspace" worked.

Can you please tell me what authorization I might miss causing this issue?

**Comment by maikvandergaag** [comment]
On which action do you receive the error amd what authentication method are you using

**Comment by rahulraajtanwar** [comment]
While using "Upload PowerBI Report" action and I have used service principle auth method.

**Comment by maikvandergaag** [comment]
What API permissions does the Service Principal have and did you try the same process by creating the workspace with the service principal by using the checkbox

**Comment by rahulraajtanwar** [comment]
API permissions: Tenant.Read.All and Tenant.ReadWrite.All

Are you asking for the below checkbox? If yes then yeah i tried that one too.
![image](https://user-images.githubusercontent.com/24808435/117105200-2b203800-ad9b-11eb-9826-970e4df8ef4c.png)

I also tried the action to create a workspace from azure devops
![image](https://user-images.githubusercontent.com/24808435/117105421-98cc6400-ad9b-11eb-8129-1ab8605b8717.png)

**Comment by maikvandergaag** [comment]
Don't think that that are the required permissions for the PowerBI API I will need to check.

Could you also share your log file when system.debug is added as variable?

**Comment by rahulraajtanwar** [comment]
Can you please tell me how to add "system.debug" variable and where?

**Comment by maikvandergaag** [comment]
It is just a Azure DevOps variable. Add it as a pipeline variable with the name system.debug and the value true

**Comment by rahulraajtanwar** [comment]
2021-05-05T08:26:12.8495899Z ##[debug]8:26:12 AM - New-PowerBIReport begin processing with ParameterSet Workspace.
2021-05-05T08:26:12.8514138Z ##[debug]8:26:12 AM - Cmdlet version: 1.0.896.0
2021-05-05T08:26:14.4070734Z Done processing Power BI Actions
2021-05-05T08:26:14.4140721Z ##[debug]Caught exception from task script.
2021-05-05T08:26:14.4171561Z ##[debug]Error record:
2021-05-05T08:26:14.5241770Z ##[debug]New-PowerBIReport : Operation returned an invalid status code 'Unauthorized'
2021-05-05T08:26:14.5253338Z ##[debug]At D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.3.32\ps_modules\PowerBi\PowerBi.psm1:771 char:9
2021-05-05T08:26:14.5272060Z ##[debug]+         New-PowerBIReport -Path $FilePath -Name $fileNamewithoutexten ...
2021-05-05T08:26:14.5278223Z ##[debug]+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-05-05T08:26:14.5293566Z ##[debug]    + CategoryInfo          : WriteError: (Microsoft.Power...ewPowerBIReport:NewPowerBIReport) [New-PowerBIReport], Ht    tpOperationException
2021-05-05T08:26:14.5303484Z ##[debug]    + FullyQualifiedErrorId : Operation returned an invalid status code 'Unauthorized',Microsoft.PowerBI.Commands.Repo    rts.NewPowerBIReport
2021-05-05T08:26:14.5315527Z ##[debug] 
2021-05-05T08:26:14.5353358Z ##[debug]Script stack trace:
2021-05-05T08:26:14.5392134Z ##[debug]at Publish-PowerBIFile, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.3.32\ps_modules\PowerBi\PowerBi.psm1: line 771
2021-05-05T08:26:14.5404761Z ##[debug]at <ScriptBlock><Process>, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.3.32\run.ps1: line 79
2021-05-05T08:26:14.5418245Z ##[debug]at <ScriptBlock>, <No file>: line 1
2021-05-05T08:26:14.5430790Z ##[debug]at <ScriptBlock>, <No file>: line 22
2021-05-05T08:26:14.5443451Z ##[debug]at <ScriptBlock>, <No file>: line 18
2021-05-05T08:26:14.5454900Z ##[debug]at <ScriptBlock>, <No file>: line 1
2021-05-05T08:26:14.5474747Z ##[debug]Exception:
2021-05-05T08:26:14.5561108Z ##[debug]Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'Unauthorized'
2021-05-05T08:26:14.5573771Z ##[debug]   at Microsoft.PowerBI.Api.V2.Imports.<UploadFile>d__8.MoveNext()
2021-05-05T08:26:14.5586646Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2021-05-05T08:26:14.5598607Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-05T08:26:14.5660593Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-05T08:26:14.5661561Z ##[debug]   at Microsoft.PowerBI.Api.V2.Imports.<PostImportFileWithHttpMessage>d__7.MoveNext()
2021-05-05T08:26:14.5662383Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2021-05-05T08:26:14.5663227Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-05T08:26:14.5664042Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-05T08:26:14.5670721Z ##[debug]   at Microsoft.PowerBI.Api.V2.ImportsExtensions.PostImportWithFileInGroup(IImports operations, String groupId, Stream fileStream, String datasetDisplayName, String nameConflict, Nullable`1 skipReport)
2021-05-05T08:26:14.5682372Z ##[debug]   at Microsoft.PowerBI.Common.Api.Reports.ReportsClient.PostImportForWorkspace(Guid workspaceId, String datasetDisplayName, String filePath, ImportConflictHandlerModeEnum nameConflict)
2021-05-05T08:26:14.5905359Z ##[debug]   at Microsoft.PowerBI.Common.Api.Reports.ReportsClient.PostReportForWorkspace(Guid workspaceId, String reportName, String filePath, ImportConflictHandlerModeEnum nameConflict, Int32 timeout)
2021-05-05T08:26:14.5917538Z ##[debug]   at Microsoft.PowerBI.Commands.Reports.NewPowerBIReport.ExecuteCmdlet()
2021-05-05T08:26:14.5955470Z ##[debug]   at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
2021-05-05T08:26:14.5984663Z ##[error]Operation returned an invalid status code 'Unauthorized'
2021-05-05T08:26:14.5986391Z ##[debug]Processed: ##vso[task.logissue type=error]Operation returned an invalid status code 'Unauthorized'
2021-05-05T08:26:14.5999705Z ##[debug]Processed: ##vso[task.complete result=Failed]
2021-05-05T08:26:14.6916399Z ##[section]Finishing: Power BI Action: Publish

**Comment by rahulraajtanwar** [comment]
It is a blocker for me. Can you please help to resolve this?

**Comment by SaurabhRuikar** [comment]
Hello. I am facing the same issue where in I get unauthorized message when using the 'Upload Power BI Report' functionality. May I know which particular API Permissions we need to have added on our Service Principal for using this? Thanks

**Comment by rahulraajtanwar** [comment]
@maikvandergaag  Have you found any solution?

**Comment by maikvandergaag** [comment]
Not yet, could you try re creating the spn?

**Comment by rahulraajtanwar** [comment]
We created the spn recently, is there any possible change that we should look for?

**Comment by GetSpiffed** [comment]
Hello, I'm having the exact same issue, I can create a workspace and assign it a user, but uploading a pbix results in a unauthorized error...

**Comment by maikvandergaag** [comment]
@GetSpiffed did you create everything by hand before deploying?

**Comment by GetSpiffed** [comment]
@maikvandergaag I just discovered that uploading to a workspasce created in the same pipeline does work! it's indeed was a manualy created workspace that is causing this probem.

**Comment by maikvandergaag** [comment]
Thanks for getting that verified. I will try to investigate further what this issue seems to be

**Comment by sachintanwar2206** [comment]
@maikvandergaag I am not able to create workspace using the pipeline (same error).

**Comment by maikvandergaag** [comment]
@sachintanwar2206: could you share more information.

**Comment by sachintanwar2206** [comment]
I am @rahulraajtanwar 😅 . It is my personal account.
