### ISSUE TITLE
Upload PBIX fails with Bad Request

### ISSUE THREAD

**Issue by Alin-Dumitrescu** [maikvandergaag/msft-extensions#312]
Hello,

I am trying to upload a vanilla pbix file and i a getting an error - what could be the issue?

2021-10-15T01:33:22.9450102Z Trying to publish PowerBI File: D:\a\r1\a\drop\drop\pbix\PipelineReport.pbix
2021-10-15T01:33:22.9525074Z Checking for existing Reports with the name: PipelineReport
2021-10-15T01:33:22.9599697Z ##[debug]1:33:22 AM - New-PowerBIReport begin processing with ParameterSet Workspace.
2021-10-15T01:33:22.9646541Z ##[debug]1:33:22 AM - Cmdlet version: 1.0.896.0
2021-10-15T01:33:23.3152175Z Done processing Power BI Actions
2021-10-15T01:33:23.3238216Z ##[debug]Caught exception from task script.
2021-10-15T01:33:23.3293069Z ##[debug]Error record:
2021-10-15T01:33:23.5183055Z ##[debug]New-PowerBIReport : Operation returned an invalid status code 'BadRequest'
2021-10-15T01:33:23.5249756Z ##[debug]At D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.3.34\ps_modules\PowerBi\PowerBi.psm1:772 char:13
2021-10-15T01:33:23.5256902Z ##[debug]+             New-PowerBIReport -Path $FilePath -Name $fileNamewithoute ...
2021-10-15T01:33:23.5278556Z ##[debug]+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-10-15T01:33:23.5308958Z ##[debug]    + CategoryInfo          : WriteError: (Microsoft.Power...ewPowerBIReport:NewPowerBIReport) [New-PowerBIReport], Ht    tpOperationException
2021-10-15T01:33:23.5356339Z ##[debug]    + FullyQualifiedErrorId : Operation returned an invalid status code 'BadRequest',Microsoft.PowerBI.Commands.Report    s.NewPowerBIReport
2021-10-15T01:33:23.5385767Z ##[debug] 
2021-10-15T01:33:23.5419948Z ##[debug]Script stack trace:
2021-10-15T01:33:23.5500389Z ##[debug]at Publish-PowerBIFile, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.3.34\ps_modules\PowerBi\PowerBi.psm1: line 772
2021-10-15T01:33:23.5556394Z ##[debug]at <ScriptBlock><Process>, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.3.34\run.ps1: line 87
2021-10-15T01:33:23.5580873Z ##[debug]at <ScriptBlock>, <No file>: line 1
2021-10-15T01:33:23.5606725Z ##[debug]at <ScriptBlock>, <No file>: line 22
2021-10-15T01:33:23.5640780Z ##[debug]at <ScriptBlock>, <No file>: line 18
2021-10-15T01:33:23.5664198Z ##[debug]at <ScriptBlock>, <No file>: line 1
2021-10-15T01:33:23.5745298Z ##[debug]Exception:
2021-10-15T01:33:23.5842185Z ##[debug]Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'BadRequest'
2021-10-15T01:33:23.5885491Z ##[debug]   at Microsoft.PowerBI.Api.V2.Imports.<UploadFile>d__8.MoveNext()
2021-10-15T01:33:23.5908707Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2021-10-15T01:33:23.5975564Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-10-15T01:33:23.6017210Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-10-15T01:33:23.6075418Z ##[debug]   at Microsoft.PowerBI.Api.V2.Imports.<PostImportFileWithHttpMessage>d__7.MoveNext()
2021-10-15T01:33:23.6102571Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2021-10-15T01:33:23.6129581Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-10-15T01:33:23.6181559Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-10-15T01:33:23.6206114Z ##[debug]   at Microsoft.PowerBI.Api.V2.ImportsExtensions.PostImportWithFileInGroup(IImports operations, String groupId, Stream fileStream, String datasetDisplayName, String nameConflict, Nullable`1 skipReport)
2021-10-15T01:33:23.6229131Z ##[debug]   at Microsoft.PowerBI.Common.Api.Reports.ReportsClient.PostImportForWorkspace(Guid workspaceId, String datasetDisplayName, String filePath, ImportConflictHandlerModeEnum nameConflict)
2021-10-15T01:33:23.6285691Z ##[debug]   at Microsoft.PowerBI.Common.Api.Reports.ReportsClient.PostReportForWorkspace(Guid workspaceId, String reportName, String filePath, ImportConflictHandlerModeEnum nameConflict, Int32 timeout)
2021-10-15T01:33:23.6314956Z ##[debug]   at Microsoft.PowerBI.Commands.Reports.NewPowerBIReport.ExecuteCmdlet()
2021-10-15T01:33:23.6371393Z ##[debug]   at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
2021-10-15T01:33:23.6475676Z ##[error]Operation returned an invalid status code 'BadRequest'
2021-10-15T01:33:23.6478043Z ##[debug]Processed: ##vso[task.logissue type=error]Operation returned an invalid status code 'BadRequest'
2021-10-15T01:33:23.6503063Z ##[debug]Processed: ##vso[task.complete result=Failed]
2021-10-15T01:33:23.7054968Z ##[section]Finishing: Power BI Action: Publish

**Comment by maikvandergaag** [comment]
Is published to production and should be available in version 5.4.9
