### ISSUE TITLE
Unable to deploy the pbix files using PBI action task-- Failed with an exception "BadRequest"

### ISSUE THREAD

**Issue by swagat2020** [maikvandergaag/msft-extensions#340]
Created a release pipeline to deploy pbix files into the PowerBI workspace using PBI action task unde Azure DevOps.
During the PBIX files deployment I'm getting following exception:
--------------------------------------------------------------------------------------------------------------------------------------
2021-11-13T20:19:15.5026315Z ##[debug]+ ...   $report = New-PowerBIReport -Path $filePath -Name $fileToPublish -W ...
2021-11-13T20:19:15.5038319Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-11-13T20:19:15.5055591Z ##[debug]    + CategoryInfo          : WriteError: (Microsoft.Power...ewPowerBIReport:NewPowerBIReport) [New-PowerBIReport], Ht    tpOperationException
2021-11-13T20:19:15.5071708Z ##[debug]    + FullyQualifiedErrorId : Operation returned an invalid status code 'BadRequest',Microsoft.PowerBI.Commands.Report    s.NewPowerBIReport
2021-11-13T20:19:15.5083829Z ##[debug] 
2021-11-13T20:19:15.5103477Z ##[debug]Script stack trace:
2021-11-13T20:19:15.5136677Z ##[debug]at Publish-PowerBIFile, C:\Users\admin_1\Documents\vsts-agent-win-x64-2.194.0\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.20\ps_modules\PowerBI\PowerBI.psm1: line 785
2021-11-13T20:19:15.5151116Z ##[debug]at <ScriptBlock><Process>, C:\Users\admin_1\Documents\vsts-agent-win-x64-2.194.0\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.20\run.ps1: line 103
2021-11-13T20:19:15.5163012Z ##[debug]at <ScriptBlock>, <No file>: line 1
2021-11-13T20:19:15.5175522Z ##[debug]at <ScriptBlock>, <No file>: line 22
2021-11-13T20:19:15.5187484Z ##[debug]at <ScriptBlock>, <No file>: line 18
2021-11-13T20:19:15.5201536Z ##[debug]at <ScriptBlock>, <No file>: line 1
2021-11-13T20:19:15.5219259Z ##[debug]Exception:
2021-11-13T20:19:15.5309278Z ##[debug]Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'BadRequest'
2021-11-13T20:19:15.5475151Z ##[debug]   at Microsoft.PowerBI.Api.V2.Imports.<UploadFile>d__8.MoveNext()
2021-11-13T20:19:15.5486891Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2021-11-13T20:19:15.5500274Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-11-13T20:19:15.5516377Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-11-13T20:19:15.5529538Z ##[debug]   at Microsoft.PowerBI.Api.V2.Imports.<PostImportFileWithHttpMessage>d__7.MoveNext()
2021-11-13T20:19:15.5543795Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2021-11-13T20:19:15.5557290Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-11-13T20:19:15.5569034Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-11-13T20:19:15.5580544Z ##[debug]   at Microsoft.PowerBI.Api.V2.ImportsExtensions.PostImportWithFileInGroup(IImports operations, String groupId, Stream fileStream, String datasetDisplayName, String nameConflict, Nullable`1 skipReport)
2021-11-13T20:19:15.5594073Z ##[debug]   at Microsoft.PowerBI.Common.Api.Reports.ReportsClient.PostImportForWorkspace(Guid workspaceId, String datasetDisplayName, String filePath, ImportConflictHandlerModeEnum nameConflict)
2021-11-13T20:19:15.5607532Z ##[debug]   at Microsoft.PowerBI.Common.Api.Reports.ReportsClient.PostReportForWorkspace(Guid workspaceId, String reportName, String filePath, ImportConflictHandlerModeEnum nameConflict, Int32 timeout)
2021-11-13T20:19:15.5619074Z ##[debug]   at Microsoft.PowerBI.Commands.Reports.NewPowerBIReport.ExecuteCmdlet()
2021-11-13T20:19:15.5631483Z ##[debug]   at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
2021-11-13T20:19:15.6032556Z ##[error]Operation returned an invalid status code 'BadRequest'
2021-11-13T20:19:15.6041238Z ##[debug]Processed: ##vso[task.logissue type=error]Operation returned an invalid status code 'BadRequest'
2021-11-13T20:19:15.6054606Z ##[debug]Processed: ##vso[task.complete result=Failed]
2021-11-13T20:19:15.6267869Z ##[section]Finishing: Power BI Action: Publish
------------------------------------------------------------------------------------------------------------------------------------------
**Note :** Execution of direct command  is successful from PowerShell prompt.
New-PowerBIReport -Path 'C:\Users\swagat\Documents\Brand Activation.pbix' -Name 'Report' -Workspace ( Get-PowerBIWorkspace -Name '<here>' )

**Comment by maikvandergaag** [comment]
Could you share some more information like logs and screenshots of you configuraiton?
