### ISSUE TITLE
One or more errors occurred

### ISSUE THREAD

**Issue by gaung-maxgeo** [maikvandergaag/msft-extensions#365]
Hi , Currently I having issue with release.

I didn't get exact error details.

![image](https://user-images.githubusercontent.com/84765800/150485584-b8dc42fd-57f8-4742-9920-81ba4e9394bc.png)

![image](https://user-images.githubusercontent.com/84765800/150485686-6b11254e-cb0b-4a4a-a317-d1e054290fb6.png)

**Comment by maikvandergaag** [comment]
Could you set the variable System.debug to true and then send the complete log file

**Comment by gaung-maxgeo** [comment]
> Could you set the variable System.debug to true and then send the complete log file

I'm pretty new on DevOps. Would you please tell me where should I put 'System.debug' setting? Thank you so much..

**Comment by maikvandergaag** [comment]
In the variables

**Comment by gaung-maxgeo** [comment]
I rereceived this error msg in debug mode, would you please tell me exactly what happened.. Thanks

2022-01-24T00:56:35.2701274Z Done processing Power BI Actions
2022-01-24T00:56:35.2805992Z ##[debug]Caught exception from task script.
2022-01-24T00:56:35.2902356Z ##[debug]Error record:
2022-01-24T00:56:35.3602661Z ##[debug]Connect-PowerBIServiceAccount : One or more errors occurred.
2022-01-24T00:56:35.3621945Z ##[debug]At D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.28\run.ps1:46 char:5
2022-01-24T00:56:35.4149813Z ##[debug]+ ...             Connect-PowerBIServiceAccount -Environment $organizationT ...
2022-01-24T00:56:35.4168458Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-01-24T00:56:35.4184991Z ##[debug]    + CategoryInfo          : WriteError: (Microsoft.Power...IServiceAccount:ConnectPowerBIServiceAccount) [Connect-Po    werBIServiceAccount], AggregateException
2022-01-24T00:56:35.4245658Z ##[debug]    + FullyQualifiedErrorId : One or more errors occurred.,Microsoft.PowerBI.Commands.Profile.ConnectPowerBIServiceAcc    ount
2022-01-24T00:56:35.4263077Z ##[debug] 
2022-01-24T00:56:35.4291778Z ##[debug]Script stack trace:
2022-01-24T00:56:35.4341976Z ##[debug]at <ScriptBlock><Process>, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.28\run.ps1: line 46
2022-01-24T00:56:35.4358440Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-01-24T00:56:35.4374904Z ##[debug]at <ScriptBlock>, <No file>: line 22
2022-01-24T00:56:35.4390539Z ##[debug]at <ScriptBlock>, <No file>: line 18
2022-01-24T00:56:35.4408300Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-01-24T00:56:35.4439417Z ##[debug]Exception:
2022-01-24T00:56:35.4565188Z ##[debug]System.AggregateException: One or more errors occurred. ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS7000215: Invalid client secret is provided.
2022-01-24T00:56:35.4586922Z ##[debug]Trace ID: 60f2e3db-cc2e-4ce0-adc9-7ec4d2434f00
2022-01-24T00:56:35.4604417Z ##[debug]Correlation ID: c57bae28-01e5-40fa-8433-5ded7d874776
2022-01-24T00:56:35.4623497Z ##[debug]Timestamp: 2022-01-24 00:56:35Z ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized). ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: 60f2e3db-cc2e-4ce0-adc9-7ec4d2434f00\r\nCorrelation ID: c57bae28-01e5-40fa-8433-5ded7d874776\r\nTimestamp: 2022-01-24 00:56:35Z","error_codes":[7000215],"timestamp":"2022-01-24 00:56:35Z","trace_id":"60f2e3db-cc2e-4ce0-adc9-7ec4d2434f00","correlation_id":"c57bae28-01e5-40fa-8433-5ded7d874776","error_uri":"https://login.microsoftonline.com/error?code=7000215"}: Unknown error
2022-01-24T00:56:35.4640636Z ##[debug]   --- End of inner exception stack trace ---
2022-01-24T00:56:35.4661541Z ##[debug]   --- End of inner exception stack trace ---
2022-01-24T00:56:35.4682296Z ##[debug]   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.AdalHttpClient.<GetResponseAsync>d__22`1.MoveNext()
2022-01-24T00:56:35.4736003Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-01-24T00:56:35.4760194Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-01-24T00:56:35.4786876Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-01-24T00:56:35.4831802Z ##[debug]   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.AdalHttpClient.<GetResponseAsync>d__21`1.MoveNext()
2022-01-24T00:56:35.4851910Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-01-24T00:56:35.4873960Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-01-24T00:56:35.4895796Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-01-24T00:56:35.4920434Z ##[debug]   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<SendHttpMessageAsync>d__72.MoveNext()
2022-01-24T00:56:35.4979459Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-01-24T00:56:35.5032667Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-01-24T00:56:35.5053579Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-01-24T00:56:35.5074157Z ##[debug]   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__69.MoveNext()
2022-01-24T00:56:35.5120302Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-01-24T00:56:35.5140424Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-01-24T00:56:35.5160580Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-01-24T00:56:35.5231847Z ##[debug]   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<CheckAndAcquireTokenUsingBroker>d__59.MoveNext()
2022-01-24T00:56:35.5250409Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-01-24T00:56:35.5298570Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-01-24T00:56:35.5318440Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-01-24T00:56:35.5339055Z ##[debug]   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__57.MoveNext()
2022-01-24T00:56:35.5358173Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-01-24T00:56:35.5374483Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-01-24T00:56:35.5406990Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-01-24T00:56:35.5424306Z ##[debug]   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenForClientCommonAsync>d__33.MoveNext()
2022-01-24T00:56:35.5440933Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-01-24T00:56:35.5457356Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-01-24T00:56:35.5474166Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-01-24T00:56:35.5493154Z ##[debug]   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__59.MoveNext()
2022-01-24T00:56:35.5509729Z ##[debug]   --- End of inner exception stack trace ---
2022-01-24T00:56:35.5527821Z ##[debug]   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
2022-01-24T00:56:35.5548304Z ##[debug]   at Microsoft.PowerBI.Common.Authentication.ServicePrincipalAuthenticationFactory.Authenticate(String userName, SecureString password, IPowerBIEnvironment environment, IPowerBILogger logger, IPowerBISettings settings)
2022-01-24T00:56:35.5568481Z ##[debug]   at Microsoft.PowerBI.Commands.Profile.ConnectPowerBIServiceAccount.ExecuteCmdlet()
2022-01-24T00:56:35.5633063Z ##[debug]   at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
2022-01-24T00:56:35.5658823Z ##[debug]---> (Inner Exception #0) Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS7000215: Invalid client secret is provided.
2022-01-24T00:56:35.5673334Z ##[debug]Trace ID: 60f2e3db-cc2e-4ce0-adc9-7ec4d2434f00
2022-01-24T00:56:35.5716556Z ##[debug]Correlation ID: c57bae28-01e5-40fa-8433-5ded7d874776
2022-01-24T00:56:35.5747456Z ##[debug]Timestamp: 2022-01-24 00:56:35Z ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized). ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: 60f2e3db-cc2e-4ce0-adc9-7ec4d2434f00\r\nCorrelation ID: c57bae28-01e5-40fa-8433-5ded7d874776\r\nTimestamp: 2022-01-24 00:56:35Z","error_codes":[7000215],"timestamp":"2022-01-24 00:56:35Z","trace_id":"60f2e3db-cc2e-4ce0-adc9-7ec4d2434f00","correlation_id":"c57bae28-01e5-40fa-8433-5ded7d874776","error_uri":"https://login.microsoftonline.com/error?code=7000215"}: Unknown error
2022-01-24T00:56:35.5763626Z ##[debug]   --- End of inner exception stack trace ---
2022-01-24T00:56:35.5807462Z ##[debug]   --- End of inner exception stack trace ---
2022-01-24T00:56:35.5828742Z ##[debug]   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.AdalHttpClient.<GetResponseAsync>d__22`1.MoveNext()
2022-01-24T00:56:35.5846040Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-01-24T00:56:35.5863094Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-01-24T00:56:35.5908111Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-01-24T00:56:35.5954584Z ##[debug]   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.AdalHttpClient.<GetResponseAsync>d__21`1.MoveNext()
2022-01-24T00:56:35.5972755Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-01-24T00:56:35.6018421Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-01-24T00:56:35.6038483Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-01-24T00:56:35.6058414Z ##[debug]   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<SendHttpMessageAsync>d__72.MoveNext()
2022-01-24T00:56:35.6085004Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-01-24T00:56:35.6108957Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-01-24T00:56:35.6131301Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-01-24T00:56:35.6157113Z ##[debug]   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__69.MoveNext()
2022-01-24T00:56:35.6182922Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-01-24T00:56:35.6260244Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-01-24T00:56:35.6330126Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-01-24T00:56:35.6331369Z ##[debug]   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<CheckAndAcquireTokenUsingBroker>d__59.MoveNext()
2022-01-24T00:56:35.6342473Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-01-24T00:56:35.6360368Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-01-24T00:56:35.6380853Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-01-24T00:56:35.6397997Z ##[debug]   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__57.MoveNext()
2022-01-24T00:56:35.6444910Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-01-24T00:56:35.6464653Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-01-24T00:56:35.6543948Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-01-24T00:56:35.6560108Z ##[debug]   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenForClientCommonAsync>d__33.MoveNext()
2022-01-24T00:56:35.6583174Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-01-24T00:56:35.6597869Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-01-24T00:56:35.6618986Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-01-24T00:56:35.6639433Z ##[debug]   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__59.MoveNext()
2022-01-24T00:56:35.6656912Z ##[debug]	ErrorCode: invalid_client
2022-01-24T00:56:35.6676671Z ##[debug]	StatusCode: 401<---
2022-01-24T00:56:35.6693671Z ##[debug]
2022-01-24T00:56:35.6996799Z ##[error]One or more errors occurred.
2022-01-24T00:56:35.7005344Z ##[debug]Processed: ##vso[task.logissue type=error]One or more errors occurred.
2022-01-24T00:56:35.7007843Z ##[debug]Processed: ##vso[task.complete result=Failed]
2022-01-24T00:56:35.7383389Z ##[section]Finishing: Power BI Action: Publish

**Comment by maikvandergaag** [comment]
The supplied credentials for the service connection are not correct

**Comment by gaung-maxgeo** [comment]
Thank you so much.. I strated AD group setup from scratch again. Everything running fine now.
