### ISSUE TITLE
SQL Credentials update action - Response status code does not indicate success: 400 (Bad Request). 

### ISSUE THREAD

**Issue by nagu-git** [maikvandergaag/msft-extensions#368]
Hi @maikvandergaag 

While updating SQL credentials action, getting bad request as response. 
Not sure how or what might the issue, kindly guide me. 

Pasted debug below below.

`
 ##[debug]4:37:16 PM - Invoke-PowerBIRestMethod begin processing with ParameterSet __AllParameterSets.
 ##[debug]4:37:16 PM - Cmdlet version: 1.0.896.0
 Done processing Power BI Actions
 ##[debug]Caught exception from task script.
 ##[debug]Error record:
 ##[debug]Invoke-PowerBIRestMethod : One or more errors occurred.
 ##[debug]At D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.28\ps_modules\PowerBI\PowerBI.psm1:1060 char:13
 ##[debug]+             Invoke-PowerBIRestMethod -Url $ApiUrl -Method Patch -Body ...
 ##[debug]+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ##[debug]    + CategoryInfo          : WriteError: (Microsoft.Power...werBIRestMethod:InvokePowerBIRestMethod) [Invoke-PowerBIR    estMethod], AggregateException
 ##[debug]    + FullyQualifiedErrorId : One or more errors occurred.,Microsoft.PowerBI.Commands.Profile.InvokePowerBIRestMethod
 ##[debug] 
 ##[debug]Script stack trace:
 ##[debug]at Update-BasicSQLDataSourceCredentials, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.28\ps_modules\PowerBI\PowerBI.psm1: line 1060
 ##[debug]at <ScriptBlock><Process>, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.28\run.ps1: line 177
 ##[debug]at <ScriptBlock>, <No file>: line 1
 ##[debug]at <ScriptBlock>, <No file>: line 22
 ##[debug]at <ScriptBlock>, <No file>: line 18
 ##[debug]at <ScriptBlock>, <No file>: line 1
 ##[debug]Exception:
 ##[debug]System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
 ##[debug]   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
 ##[debug]   at Microsoft.PowerBI.Commands.Profile.InvokePowerBIRestMethod.<InvokeRestMethod>d__35.MoveNext()
 ##[debug]   --- End of inner exception stack trace ---
 ##[debug]   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
 ##[debug]   at Microsoft.PowerBI.Commands.Profile.InvokePowerBIRestMethod.ExecuteCmdlet()
 ##[debug]   at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
 ##[debug]---> (Inner Exception #0) System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
 ##[debug]   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
 ##[debug]   at Microsoft.PowerBI.Commands.Profile.InvokePowerBIRestMethod.<InvokeRestMethod>d__35.MoveNext()<---
 ##[debug]
 ##[error]One or more errors occurred.
 ##[debug]Processed: ##vso[task.logissue type=error]One or more errors occurred.
 ##[debug]Processed: ##vso[task.complete result=Failed] `

**Comment by dileeprajam** [comment]
> Please ignore above issue.
> 
> Thanks

Hi I am also receiving the above error message. can you please help how did you resolve or what was the cause of your error

thanks,
-Dileep

**Comment by PeterAllenspach** [comment]
@nagu-git Also getting the same error. Would you mind providing some information on what was your resolution?
Thanks Peter
