### ISSUE TITLE
Getting "The remote server returned an error: (400) Bad Request." when pushing report to PBI workspace from azure devops pipelines

### ISSUE THREAD

**Issue by saiudthawar** [maikvandergaag/msft-extensions#371]
I have azure devops ci/cd for pushing report and datasets into powerbi. so when trying to push reports into workspace in powerBi I'm getting error 400.

This is the log File.

2022-02-21T19:10:06.4103569Z ##[debug]Evaluating condition for step: 'Power BI Longwall: Publish to Test'
2022-02-21T19:10:06.4106197Z ##[debug]Evaluating: succeeded()
2022-02-21T19:10:06.4106973Z ##[debug]Evaluating succeeded:
2022-02-21T19:10:06.4108786Z ##[debug]=> True
2022-02-21T19:10:06.4109437Z ##[debug]Result: True
2022-02-21T19:10:06.4110141Z ##[section]Starting: Power BI Longwall: Publish to Test
2022-02-21T19:10:06.4309021Z ==============================================================================
2022-02-21T19:10:06.4309345Z Task         : Power BI Actions
2022-02-21T19:10:06.4309596Z Description  : Release Task Power BI Actions
2022-02-21T19:10:06.4310038Z Version      : 4.1.19
2022-02-21T19:10:06.4310240Z Author       : Maik van der Gaag
2022-02-21T19:10:06.4311045Z Help         : 
2022-02-21T19:10:06.4311309Z ==============================================================================
2022-02-21T19:10:11.8048881Z ##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
2022-02-21T19:10:12.1560546Z ##[debug]Entering D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\4.1.19\run.ps1.
2022-02-21T19:10:12.1723417Z ##[debug]Loading module from path 'D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\4.1.19\ps_modules\PowerBi\PowerBi.psm1'.
2022-02-21T19:10:12.1928068Z ##[debug]Exporting function 'Invoke-API'.
2022-02-21T19:10:12.1959971Z ##[debug]Exporting function 'New-DatasetRefresh'.
2022-02-21T19:10:12.1991010Z ##[debug]Exporting function 'Get-PowerBIWorkspace'.
2022-02-21T19:10:12.2028216Z ##[debug]Exporting function 'Update-PowerBIDatasetDatasources'.
2022-02-21T19:10:12.2068382Z ##[debug]Exporting function 'Update-PowerBIDatasetDatasource'.
2022-02-21T19:10:12.2097301Z ##[debug]Exporting function 'Update-ConnectionStringDirectQuery'.
2022-02-21T19:10:12.2189337Z ##[debug]Exporting function 'Get-PowerBIReport'.
2022-02-21T19:10:12.2229817Z ##[debug]Exporting function 'Get-PowerBiDataSet'.
2022-02-21T19:10:12.2259819Z ##[debug]Exporting function 'Get-PowerBiDataSets'.
2022-02-21T19:10:12.2310340Z ##[debug]Exporting function 'New-PowerBIWorkSpace'.
2022-02-21T19:10:12.2339476Z ##[debug]Exporting function 'Remove-PowerBIWorkSpace'.
2022-02-21T19:10:12.2375623Z ##[debug]Exporting function 'Import-PowerBIFile'.
2022-02-21T19:10:12.2403637Z ##[debug]Exporting function 'Get-PowerBIGroupPath'.
2022-02-21T19:10:12.2446380Z ##[debug]Exporting function 'Add-PowerBIWorkspaceUsers'.
2022-02-21T19:10:12.2509484Z ##[debug]Exporting function 'Add-PowerBIWorkspaceGroup'.
2022-02-21T19:10:12.2539896Z ##[debug]Exporting function 'Add-PowerBIWorkspaceSP'.
2022-02-21T19:10:12.2638526Z ##[debug]Exporting function 'Publish-PowerBIFile'.
2022-02-21T19:10:12.2688065Z ##[debug]Exporting variable 'powerbiUrl'.
2022-02-21T19:10:12.2815088Z ##[debug]Importing function 'Add-PowerBIWorkspaceGroup'.
2022-02-21T19:10:12.2877642Z ##[debug]Importing function 'Add-PowerBIWorkspaceSP'.
2022-02-21T19:10:12.2914817Z ##[debug]Importing function 'Add-PowerBIWorkspaceUsers'.
2022-02-21T19:10:12.2949275Z ##[debug]Importing function 'Get-PowerBiDataSet'.
2022-02-21T19:10:12.3012698Z ##[debug]Importing function 'Get-PowerBiDataSets'.
2022-02-21T19:10:12.3082010Z ##[debug]Importing function 'Get-PowerBIGroupPath'.
2022-02-21T19:10:12.3162069Z ##[debug]Importing function 'Get-PowerBIReport'.
2022-02-21T19:10:12.3198325Z ##[debug]Importing function 'Get-PowerBIWorkspace'.
2022-02-21T19:10:12.3241540Z ##[debug]Importing function 'Import-PowerBIFile'.
2022-02-21T19:10:12.3341614Z ##[debug]Importing function 'Invoke-API'.
2022-02-21T19:10:12.3395641Z ##[debug]Importing function 'New-DatasetRefresh'.
2022-02-21T19:10:12.4633196Z ##[debug]Importing function 'New-PowerBIWorkSpace'.
2022-02-21T19:10:12.4678642Z ##[debug]Importing function 'Publish-PowerBIFile'.
2022-02-21T19:10:12.4712536Z ##[debug]Importing function 'Remove-PowerBIWorkSpace'.
2022-02-21T19:10:12.4743999Z ##[debug]Importing function 'Update-ConnectionStringDirectQuery'.
2022-02-21T19:10:12.4789692Z ##[debug]Importing function 'Update-PowerBIDatasetDatasource'.
2022-02-21T19:10:12.4948998Z ##[debug]Importing function 'Update-PowerBIDatasetDatasources'.
2022-02-21T19:10:12.5013046Z ##[debug]Importing variable 'powerbiUrl'.
2022-02-21T19:10:12.5079347Z ##[debug]Loading module from path 'D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\4.1.19\ps_modules\ADAL.PS\ADAL.PS.psd1'.
2022-02-21T19:10:12.5278085Z ##[debug]Loading 'Assembly' from path 'D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\4.1.19\ps_modules\ADAL.PS\Microsoft.IdentityModel.Clients.ActiveDirectory.3.19.8\Microsoft.IdentityModel.Clients.ActiveDirectory.dll'.
2022-02-21T19:10:12.5361484Z ##[debug]Loading 'Assembly' from path 'D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\4.1.19\ps_modules\ADAL.PS\Microsoft.IdentityModel.Clients.ActiveDirectory.3.19.8\Microsoft.IdentityModel.Clients.ActiveDirectory.dll'.
2022-02-21T19:10:12.5420050Z ##[debug]Loading 'Assembly' from path 'D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\4.1.19\ps_modules\ADAL.PS\Microsoft.IdentityModel.Clients.ActiveDirectory.3.19.8\Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll'.
2022-02-21T19:10:12.5485135Z ##[debug]Loading 'Assembly' from path 'D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\4.1.19\ps_modules\ADAL.PS\Microsoft.IdentityModel.Clients.ActiveDirectory.3.19.8\Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll'.
2022-02-21T19:10:12.5825025Z ##[debug]Loading module from path 'D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\4.1.19\ps_modules\ADAL.PS\ADAL.PS.psm1'.
2022-02-21T19:10:12.6234476Z ##[debug]Exporting function 'Get-ADALAuthenticationContext'.
2022-02-21T19:10:12.6268926Z ##[debug]Exporting function 'New-ADALUserIdentifier'.
2022-02-21T19:10:12.6305705Z ##[debug]Exporting function 'New-ADALClientCredential'.
2022-02-21T19:10:12.6378540Z ##[debug]Exporting function 'Get-ADALToken'.
2022-02-21T19:10:12.6433207Z ##[debug]Exporting function 'Clear-ADALTokenCache'.
2022-02-21T19:10:12.6487717Z ##[debug]Importing function 'Clear-ADALTokenCache'.
2022-02-21T19:10:12.6583201Z ##[debug]Importing function 'Get-ADALAuthenticationContext'.
2022-02-21T19:10:12.6630189Z ##[debug]Importing function 'Get-ADALToken'.
2022-02-21T19:10:12.6659479Z ##[debug]Importing function 'New-ADALClientCredential'.
2022-02-21T19:10:12.6705759Z ##[debug]Importing function 'New-ADALUserIdentifier'.
2022-02-21T19:10:12.7118375Z ##[debug]INPUT_AUTHENTICATIONTYPE: 'ServicePrincipal'
2022-02-21T19:10:12.7175599Z ##[debug]INPUT_CONNECTEDSERVICENAMESP: ''
2022-02-21T19:10:12.7380588Z ##[debug]ENDPOINT_URL_0771cb7e-f048-4874-88f0-2390985562ce: 'https://api.powerbi.com/v1.0'
2022-02-21T19:10:12.7447098Z ##[debug]ENDPOINT_AUTH_0771cb7e-f048-4874-88f0-2390985562ce: '********'
2022-02-21T19:10:12.7519079Z ##[debug]ENDPOINT_DATA_0771cb7e-f048-4874-88f0-2390985562ce: '{}'
2022-02-21T19:10:12.7777428Z ******************************
2022-02-21T19:10:12.7797808Z ** Service Connection: 
2022-02-21T19:10:12.7822828Z ** TenantId: 
2022-02-21T19:10:12.7845227Z ** ClientId: ***
2022-02-21T19:10:12.7866488Z ******************************
2022-02-21T19:10:12.8669099Z ##[debug]INPUT_POWERBIPATH: 'D:\a\r1\a\_PowerBI-Longwall-Reports-CI\drop'
2022-02-21T19:10:12.8719891Z ##[debug]INPUT_WORKSPACENAME: 'Longwall DEV'
2022-02-21T19:10:12.8779526Z ##[debug]INPUT_OVERWRITE: 'true'
2022-02-21T19:10:12.8872065Z ##[debug] Converted to bool: True
2022-02-21T19:10:12.8914066Z ##[debug]INPUT_CREATE: 'false'
2022-02-21T19:10:12.8949026Z ##[debug] Converted to bool: False
2022-02-21T19:10:12.9009093Z ##[debug]INPUT_ACTION: 'Publish'
2022-02-21T19:10:12.9097141Z ##[debug]INPUT_DATASETNAME (empty)
2022-02-21T19:10:12.9172493Z ##[debug]INPUT_OLDURL (empty)
2022-02-21T19:10:12.9243674Z ##[debug]INPUT_NEWURL (empty)
2022-02-21T19:10:12.9286619Z ##[debug]INPUT_OLDSERVER (empty)
2022-02-21T19:10:12.9360128Z ##[debug]INPUT_NEWSERVER (empty)
2022-02-21T19:10:12.9412297Z ##[debug]INPUT_OLDDATABASE (empty)
2022-02-21T19:10:12.9476425Z ##[debug]INPUT_GROUPOBJECTIDS (empty)
2022-02-21T19:10:12.9522504Z ##[debug]INPUT_NEWDATABASE (empty)
2022-02-21T19:10:12.9564946Z ##[debug]INPUT_PERMISSION (empty)
2022-02-21T19:10:12.9605324Z ##[debug]INPUT_USERS (empty)
2022-02-21T19:10:12.9659632Z ##[debug]INPUT_DATASOURCETYPE: 'Sql'
2022-02-21T19:10:12.9702890Z ##[debug]INPUT_UPDATEALL: 'false'
2022-02-21T19:10:12.9767625Z ##[debug] Converted to bool: False
2022-02-21T19:10:12.9836646Z ##[debug]INPUT_SERVICEPRINCIPALS (empty)
2022-02-21T19:10:12.9965433Z ##[debug]INPUT_CONNECTIONSTRING (empty)
2022-02-21T19:10:13.0939904Z ##[debug]FilePattern           : D:\a\r1\a\_PowerBI-Longwall-Reports-KLTD-CI\drop
2022-02-21T19:10:13.0980502Z ##[debug]ClientID         	   : ***
2022-02-21T19:10:13.1069551Z ##[debug]PassWord              : <not present>
2022-02-21T19:10:13.1104668Z ##[debug]Username              : 
2022-02-21T19:10:13.1184827Z ##[debug]WorkspaceName         :Longwall DEV
2022-02-21T19:10:13.1262478Z ##[debug]Overwrite             : True
2022-02-21T19:10:13.1335884Z ##[debug]Create                : False
2022-02-21T19:10:13.1372307Z ##[debug]Action                : Publish
2022-02-21T19:10:13.1450638Z ##[debug]Dataset               : 
2022-02-21T19:10:13.1509067Z ##[debug]Users                 : 
2022-02-21T19:10:13.1563136Z ##[debug]AccessRight           : 
2022-02-21T19:10:13.1615502Z ##[debug]GroupObjectIds        : 
2022-02-21T19:10:13.1656311Z ##[debug]OldServer             : 
2022-02-21T19:10:13.1695865Z ##[debug]NewServer             : 
2022-02-21T19:10:13.1744641Z ##[debug]OldDatabase           : 
2022-02-21T19:10:13.1787062Z ##[debug]NewDatabase           : 
2022-02-21T19:10:13.1820608Z ##[debug]OldUrl                : 
2022-02-21T19:10:13.1857504Z ##[debug]NewUrl                : 
2022-02-21T19:10:13.1941454Z ##[debug]DatasourceType        : Sql
2022-02-21T19:10:13.1976366Z ##[debug]UpdateAll             : False
2022-02-21T19:10:13.2059369Z ##[debug]ClientSecret          : System.Security.SecureString
2022-02-21T19:10:13.2166390Z ##[debug]TenantId              : 
2022-02-21T19:10:13.2196323Z ##[debug]Service Principals    : 
2022-02-21T19:10:13.2316190Z ##[debug]ConnectionString     	: <not present>
2022-02-21T19:10:13.2345262Z Logging in with a Service Principal
2022-02-21T19:10:14.5731251Z Publishing PowerBI FIle: D:\a\r1\a\_PowerBI-Longwall-Reports-KLTD-CI\drop, in workspace:  Longwall DEV with user: 
2022-02-21T19:10:14.6021825Z Getting Power BI Workspace properties;  Longwall DEV
2022-02-21T19:10:14.6168020Z ##[debug]Trying to invoke api: https://api.powerbi.com/v1.0/myorg/groups
2022-02-21T19:10:14.6611399Z ##[debug]GET https://api.powerbi.com/v1.0/myorg/groups with 0-byte payload
2022-02-21T19:10:15.3329374Z ##[debug]received -1-byte response of content type application/json; odata.metadata=minimal; odata.streaming=true
2022-02-21T19:10:15.3676771Z ##[debug]Trying to find workspace: Longwall DEV
2022-02-21T19:10:15.4017321Z ##[debug]Processed: ##vso[task.setvariable variable=PowerBIActions.WorkspaceId]0dc9bfb3-43e6-47d8-b435-
2022-02-21T19:10:15.4231230Z Trying to publish PowerBI File: D:\a\r1\a\_PowerBI-Longwall-Reports-KLTD-CI\drop\KMAP SHEARER MHS REPORT CUMBERLAND1.pbix
2022-02-21T19:10:15.4285668Z Checking for existing Reports with the name: KMAP SHEARER MHS REPORT CUMBERLAND1
2022-02-21T19:10:15.4477333Z ##[debug]Trying to invoke api: https://api.powerbi.com/v1.0/myorg/groups/0dc9bfb3-43e6-47d8-/reports
2022-02-21T19:10:15.4937024Z ##[debug]GET https://api.powerbi.com/v1.0/myorg/groups/0dc9bfb3-43e6-47d8-/reports with 0-byte payload
2022-02-21T19:10:15.7476493Z ##[debug]received -1-byte response of content type application/json; odata.metadata=minimal; odata.streaming=true
2022-02-21T19:10:15.7555508Z ##[debug]Trying to find report 'KMAP SHEARER MHS REPORT CUMBERLAND1'
2022-02-21T19:10:15.7632539Z Importing PowerBI File
2022-02-21T19:10:15.9480025Z ##[debug]Trying to invoke api: https://api.powerbi.com/v1.0/myorg/groups/0dc9bfb3-43e6-47d8-/imports?datasetDisplayName=KMAP+SHEARER+MHS+REPORT+CUMBERLAND1.pbix&nameConflict=Abort
2022-02-21T19:10:16.0118756Z ##[debug]POST https://api.powerbi.com/v1.0/myorg/groups/0dc9bfb3-43e6-47d8-/imports?datasetDisplayName=KMAP+SHEARER+MHS+REPORT+CUMBERLAND1.pbix&nameConflict=Abort with -1-byte payload
2022-02-21T19:10:17.2503276Z ##[debug]Leaving D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\4.1.19\run.ps1.
2022-02-21T19:10:17.2632716Z ##[debug]Caught exception from task script.
2022-02-21T19:10:17.2683861Z ##[debug]Error record:
2022-02-21T19:10:17.4028824Z ##[debug]Invoke-API : The remote server returned an error: (400) Bad Request.
2022-02-21T19:10:17.4061242Z ##[debug]At D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-\4.1.19\ps_modules\PowerBi\PowerBi.psm1:452 char:15
2022-02-21T19:10:17.4156767Z ##[debug]+ ...   $result = Invoke-API -Url $url -Method "Post" -AccessToken $AccessT ...
2022-02-21T19:10:17.4176623Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-02-21T19:10:17.4223226Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [Write-Error], WebException
2022-02-21T19:10:17.4336780Z ##[debug]    + FullyQualifiedErrorId : System.Net.WebException,Invoke-API
2022-02-21T19:10:17.4403841Z ##[debug] 
2022-02-21T19:10:17.4473192Z ##[debug]Script stack trace:
2022-02-21T19:10:17.4564956Z ##[debug]at Invoke-API, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-9\4.1.19\ps_modules\PowerBi\PowerBi.psm1: line 148
2022-02-21T19:10:17.4594081Z ##[debug]at Import-PowerBIFile, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-\4.1.19\ps_modules\PowerBi\PowerBi.psm1: line 452
2022-02-21T19:10:17.4686918Z ##[debug]at Publish-PowerBIFile, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-\4.1.19\ps_modules\PowerBi\PowerBi.psm1: line 598
2022-02-21T19:10:17.4702159Z ##[debug]at <ScriptBlock>, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-\4.1.19\run-task.ps1: line 83
2022-02-21T19:10:17.4785214Z ##[debug]at <ScriptBlock>, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-\4.1.19\run.ps1: line 72
2022-02-21T19:10:17.4801351Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-02-21T19:10:17.4829065Z ##[debug]at <ScriptBlock>, <No file>: line 22
2022-02-21T19:10:17.4857416Z ##[debug]at <ScriptBlock>, <No file>: line 18
2022-02-21T19:10:17.4914007Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-02-21T19:10:17.4961233Z ##[debug]Exception:
2022-02-21T19:10:17.5035057Z ##[debug]System.Net.WebException: The remote server returned an error: (400) Bad Request.
2022-02-21T19:10:17.5060437Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
2022-02-21T19:10:17.5128737Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
2022-02-21T19:10:17.5519252Z ##[error]The remote server returned an error: (400) Bad Request.
2022-02-21T19:10:17.5530744Z ##[debug]Processed: ##vso[task.logissue type=error]The remote server returned an error: (400) Bad Request.
2022-02-21T19:10:17.5532939Z ##[debug]Processed: ##vso[task.complete result=Failed]
2022-02-21T19:10:17.6968124Z ##[section]Finishing: Power BI Longwall: Publish to Test

**Comment by maikvandergaag** [comment]
Which version of the actions are you using. It looks like you are not using the latest one. Could you update?
