### ISSUE TITLE
##[error]Operation returned an invalid status code 'Unauthorized'

### ISSUE THREAD

**Issue by tushmesh** [maikvandergaag/msft-extensions#373]
2022-02-24T13:50:18.3545116Z ##[section]Starting: Power BI Action: Publish
2022-02-24T13:50:18.3720340Z ==============================================================================
2022-02-24T13:50:18.3720873Z Task         : Power BI Actions
2022-02-24T13:50:18.3721133Z Description  : Release Task Power BI Actions
2022-02-24T13:50:18.3721391Z Version      : 5.4.28
2022-02-24T13:50:18.3721618Z Author       : Maik van der Gaag
2022-02-24T13:50:18.3722317Z Help         : 
2022-02-24T13:50:18.3722596Z ==============================================================================
2022-02-24T13:50:22.6871157Z Starting Power BI Actions extension
2022-02-24T13:50:22.7142654Z ### Required Module is needed. Importing now...
2022-02-24T13:50:23.0013456Z ### Trying to import the incorporated module for PowerBI
2022-02-24T13:50:25.0862443Z Getting Power BI Workspace properties; WORKSPACE
2022-02-24T13:50:26.4496592Z ##[error]Operation returned an invalid status code 'Unauthorized'
2022-02-24T13:50:27.7042281Z Done processing Power BI Actions
2022-02-24T13:50:27.7203869Z ##[error]Operation returned an invalid status code 'Unauthorized'
2022-02-24T13:50:27.8114949Z ##[section]Finishing: Power BI Action: Publish

*Note* : SPN, security group, permission at PBI admin portal and workspace is in place.
Detailed Log

2022-03-02T17:39:00.1939014Z ##[debug]Get-PowerBIWorkspace : Operation returned an invalid status code 'Unauthorized'
2022-03-02T17:39:00.1953309Z ##[debug]At D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.28\ps_modules\PowerBI\PowerBI.psm1:676 char:22
2022-03-02T17:39:00.1966534Z ##[debug]+ ...       $workspace = Get-PowerBIWorkspace -Name $WorkspaceName -Verbose
2022-03-02T17:39:00.1981506Z ##[debug]+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-03-02T17:39:00.1994616Z ##[debug]    + CategoryInfo          : WriteError: (Microsoft.Power...owerBIWorkspace:GetPowerBIWorkspace) [Get-PowerBIWorkspac    e], HttpOperationException
2022-03-02T17:39:00.2007462Z ##[debug]    + FullyQualifiedErrorId : Operation returned an invalid status code 'Unauthorized',Microsoft.PowerBI.Commands.Work    spaces.GetPowerBIWorkspace
2022-03-02T17:39:00.2019440Z ##[debug] 
2022-03-02T17:39:00.2143363Z ##[debug]Script stack trace:
2022-03-02T17:39:00.2184983Z ##[debug]at Get-PowerBIGroupPath, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.28\ps_modules\PowerBI\PowerBI.psm1: line 676
2022-03-02T17:39:00.2234459Z ##[debug]at Publish-PowerBIFile, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.28\ps_modules\PowerBI\PowerBI.psm1: line 766
2022-03-02T17:39:00.2290965Z ##[debug]at <ScriptBlock><Process>, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.28\run.ps1: line 104
2022-03-02T17:39:00.2313528Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-03-02T17:39:00.2337150Z ##[debug]at <ScriptBlock>, <No file>: line 22
2022-03-02T17:39:00.2356527Z ##[debug]at <ScriptBlock>, <No file>: line 18
2022-03-02T17:39:00.2370468Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-03-02T17:39:00.2390788Z ##[debug]Exception:
2022-03-02T17:39:00.2575788Z ##[debug]Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'Unauthorized'
2022-03-02T17:39:00.2590427Z ##[debug]   at Microsoft.PowerBI.Api.V2.Groups.<GetGroupsWithHttpMessagesAsync>d__5.MoveNext()
2022-03-02T17:39:00.2603860Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-03-02T17:39:00.2617072Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-03-02T17:39:00.2633501Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-03-02T17:39:00.2646452Z ##[debug]   at Microsoft.PowerBI.Api.V2.GroupsExtensions.<GetGroupsAsync>d__1.MoveNext()
2022-03-02T17:39:00.2659532Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-03-02T17:39:00.2672015Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-03-02T17:39:00.2684979Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-03-02T17:39:00.3233392Z ##[debug]   at Microsoft.PowerBI.Api.V2.GroupsExtensions.GetGroups(IGroups operations, String filter, Nullable`1 top, Nullable`1 skip)
2022-03-02T17:39:00.3252435Z ##[debug]   at Microsoft.PowerBI.Common.Api.Workspaces.WorkspacesClient.GetWorkspaces(String filter, Nullable`1 top, Nullable`1 skip)
2022-03-02T17:39:00.3265500Z ##[debug]   at Microsoft.PowerBI.Commands.Workspaces.GetPowerBIWorkspace.GetWorkspaces()
2022-03-02T17:39:00.3364725Z ##[debug]   at Microsoft.PowerBI.Commands.Workspaces.GetPowerBIWorkspace.ExecuteCmdlet()
2022-03-02T17:39:00.3379544Z ##[debug]   at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
2022-03-02T17:39:00.3669213Z ##[error]Operation returned an invalid status code 'Unauthorized'
*I cannot change the label to BUG*

**Comment by tushmesh** [comment]
2022-03-02T17:39:00.1939014Z ##[debug]Get-PowerBIWorkspace : Operation returned an invalid status code 'Unauthorized'
2022-03-02T17:39:00.1953309Z ##[debug]At D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.28\ps_modules\PowerBI\PowerBI.psm1:676 char:22
2022-03-02T17:39:00.1966534Z ##[debug]+ ...       $workspace = Get-PowerBIWorkspace -Name $WorkspaceName -Verbose
2022-03-02T17:39:00.1981506Z ##[debug]+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-03-02T17:39:00.1994616Z ##[debug]    + CategoryInfo          : WriteError: (Microsoft.Power...owerBIWorkspace:GetPowerBIWorkspace) [Get-PowerBIWorkspac    e], HttpOperationException
2022-03-02T17:39:00.2007462Z ##[debug]    + FullyQualifiedErrorId : Operation returned an invalid status code 'Unauthorized',Microsoft.PowerBI.Commands.Work    spaces.GetPowerBIWorkspace
2022-03-02T17:39:00.2019440Z ##[debug] 
2022-03-02T17:39:00.2143363Z ##[debug]Script stack trace:
2022-03-02T17:39:00.2184983Z ##[debug]at Get-PowerBIGroupPath, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.28\ps_modules\PowerBI\PowerBI.psm1: line 676
2022-03-02T17:39:00.2234459Z ##[debug]at Publish-PowerBIFile, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.28\ps_modules\PowerBI\PowerBI.psm1: line 766
2022-03-02T17:39:00.2290965Z ##[debug]at <ScriptBlock><Process>, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.28\run.ps1: line 104
2022-03-02T17:39:00.2313528Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-03-02T17:39:00.2337150Z ##[debug]at <ScriptBlock>, <No file>: line 22
2022-03-02T17:39:00.2356527Z ##[debug]at <ScriptBlock>, <No file>: line 18
2022-03-02T17:39:00.2370468Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-03-02T17:39:00.2390788Z ##[debug]Exception:
2022-03-02T17:39:00.2575788Z ##[debug]Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'Unauthorized'
2022-03-02T17:39:00.2590427Z ##[debug]   at Microsoft.PowerBI.Api.V2.Groups.<GetGroupsWithHttpMessagesAsync>d__5.MoveNext()
2022-03-02T17:39:00.2603860Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-03-02T17:39:00.2617072Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-03-02T17:39:00.2633501Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-03-02T17:39:00.2646452Z ##[debug]   at Microsoft.PowerBI.Api.V2.GroupsExtensions.<GetGroupsAsync>d__1.MoveNext()
2022-03-02T17:39:00.2659532Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-03-02T17:39:00.2672015Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-03-02T17:39:00.2684979Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-03-02T17:39:00.3233392Z ##[debug]   at Microsoft.PowerBI.Api.V2.GroupsExtensions.GetGroups(IGroups operations, String filter, Nullable`1 top, Nullable`1 skip)
2022-03-02T17:39:00.3252435Z ##[debug]   at Microsoft.PowerBI.Common.Api.Workspaces.WorkspacesClient.GetWorkspaces(String filter, Nullable`1 top, Nullable`1 skip)
2022-03-02T17:39:00.3265500Z ##[debug]   at Microsoft.PowerBI.Commands.Workspaces.GetPowerBIWorkspace.GetWorkspaces()
2022-03-02T17:39:00.3364725Z ##[debug]   at Microsoft.PowerBI.Commands.Workspaces.GetPowerBIWorkspace.ExecuteCmdlet()
2022-03-02T17:39:00.3379544Z ##[debug]   at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
2022-03-02T17:39:00.3669213Z ##[error]Operation returned an invalid status code 'Unauthorized'
