### ISSUE TITLE
Get-PowerBIWorkspace : Operation returned an invalid status code 'Unauthorized'

### ISSUE THREAD

**Issue by tushmesh** [maikvandergaag/msft-extensions#375]
**Version**
Task         : Power BI Actions
Description  : Release Task Power BI Actions
Version      : 5.4.28
Author       : Maik van der Gaag

**Description**
Using the SPN trying to upload .pbix files to Power BI
Steps followed:
1. SPN created
2. Security group created
3. Added security group to PowerBI Admin
4. Added SPN to workspace
5. Created the Service Connection 'Commercial (Public)'

**Logs**

2022-03-02T17:48:28.8239710Z ##[debug]5:48:28 PM - Cmdlet version: 1.0.896.0
2022-03-02T17:48:29.7300887Z ##[debug]Error record:
2022-03-02T17:48:29.8334630Z ##[debug]Get-PowerBIWorkspace : Operation returned an invalid status code 'Unauthorized'
2022-03-02T17:48:29.8336334Z ##[debug]At D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.28\ps_modules\PowerBI\PowerBI.psm1:676 char:22
2022-03-02T17:48:29.8404136Z ##[debug]+ ...       $workspace = Get-PowerBIWorkspace -Name $WorkspaceName -Verbose
2022-03-02T17:48:29.8435243Z ##[debug]+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-03-02T17:48:29.8458678Z ##[debug]    + CategoryInfo          : WriteError: (Microsoft.Power...owerBIWorkspace:GetPowerBIWorkspace) [Get-PowerBIWorkspac    e], HttpOperationException
2022-03-02T17:48:29.8530659Z ##[debug]    + FullyQualifiedErrorId : Operation returned an invalid status code 'Unauthorized',Microsoft.PowerBI.Commands.Work    spaces.GetPowerBIWorkspace
2022-03-02T17:48:29.8549867Z ##[debug] 
2022-03-02T17:48:29.8577039Z ##[debug]Script stack trace:
2022-03-02T17:48:29.8625476Z ##[debug]at Get-PowerBIGroupPath, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.28\ps_modules\PowerBI\PowerBI.psm1: line 676
2022-03-02T17:48:29.8655069Z ##[debug]at Publish-PowerBIFile, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.28\ps_modules\PowerBI\PowerBI.psm1: line 766
2022-03-02T17:48:29.8702267Z ##[debug]at <ScriptBlock><Process>, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.28\run.ps1: line 104
2022-03-02T17:48:29.8722940Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-03-02T17:48:29.8741836Z ##[debug]at <ScriptBlock>, <No file>: line 22
2022-03-02T17:48:29.8761290Z ##[debug]at <ScriptBlock>, <No file>: line 18
2022-03-02T17:48:29.8815825Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-03-02T17:48:29.8826840Z ##[debug]Exception:
2022-03-02T17:48:29.9001378Z ##[debug]Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'Unauthorized'
2022-03-02T17:48:29.9019605Z ##[debug]   at Microsoft.PowerBI.Api.V2.Groups.<GetGroupsWithHttpMessagesAsync>d__5.MoveNext()
2022-03-02T17:48:29.9045862Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-03-02T17:48:29.9119042Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-03-02T17:48:29.9177093Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-03-02T17:48:29.9192576Z ##[debug]   at Microsoft.PowerBI.Api.V2.GroupsExtensions.<GetGroupsAsync>d__1.MoveNext()
2022-03-02T17:48:29.9214604Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-03-02T17:48:29.9264617Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-03-02T17:48:29.9294242Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-03-02T17:48:29.9491720Z ##[debug]   at Microsoft.PowerBI.Api.V2.GroupsExtensions.GetGroups(IGroups operations, String filter, Nullable`1 top, Nullable`1 skip)
2022-03-02T17:48:29.9552000Z ##[debug]   at Microsoft.PowerBI.Common.Api.Workspaces.WorkspacesClient.GetWorkspaces(String filter, Nullable`1 top, Nullable`1 skip)
2022-03-02T17:48:29.9554075Z ##[debug]   at Microsoft.PowerBI.Commands.Workspaces.GetPowerBIWorkspace.GetWorkspaces()
2022-03-02T17:48:29.9573417Z ##[debug]   at Microsoft.PowerBI.Commands.Workspaces.GetPowerBIWorkspace.ExecuteCmdlet()
2022-03-02T17:48:29.9595382Z ##[debug]   at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
2022-03-02T17:48:29.9909143Z ##[error]Operation returned an invalid status code 'Unauthorized'
2022-03-02T17:48:29.9920052Z ##[debug]Processed: ##vso[task.logissue type=error]Operation returned an invalid status code 'Unauthorized'
2022-03-02T17:48:29.9921346Z ##[debug]Request Uri: https://api.powerbi.com/v1.0/myorg/groups?$filter=tolower(name) eq 'powerbitest'&$top=100
2022-03-02T17:48:29.9935085Z ##[debug]Status Code: Unauthorized (401)
2022-03-02T17:48:29.9967426Z ##[debug]5:48:29 PM - Get-PowerBIWorkspace end processing.
2022-03-02T17:48:30.0132788Z ##[debug]5:48:30 PM - Get-PowerBIWorkspace begin processing with ParameterSet Name.
2022-03-02T17:48:30.0154018Z ##[debug]5:48:30 PM - Cmdlet version: 1.0.896.0
2022-03-02T17:48:30.6910950Z Done processing Power BI Actions
2022-03-02T17:48:30.7067700Z ##[debug]Caught exception from task script.
2022-03-02T17:48:30.7103924Z ##[debug]Error record:
2022-03-02T17:48:30.7218212Z ##[debug]Get-PowerBIWorkspace : Operation returned an invalid status code 'Unauthorized'
2022-03-02T17:48:30.7245451Z ##[debug]At D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.28\ps_modules\PowerBI\PowerBI.psm1:600 char:18
2022-03-02T17:48:30.7353813Z ##[debug]+     $workspace = Get-PowerBIWorkspace -Name $WorkspaceName
2022-03-02T17:48:30.7375175Z ##[debug]+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-03-02T17:48:30.7397255Z ##[debug]    + CategoryInfo          : WriteError: (Microsoft.Power...owerBIWorkspace:GetPowerBIWorkspace) [Get-PowerBIWorkspac    e], HttpOperationException
2022-03-02T17:48:30.7438350Z ##[debug]    + FullyQualifiedErrorId : Operation returned an invalid status code 'Unauthorized',Microsoft.PowerBI.Commands.Work    spaces.GetPowerBIWorkspace
2022-03-02T17:48:30.7451514Z ##[debug] 
2022-03-02T17:48:30.7479111Z ##[debug]Script stack trace:
2022-03-02T17:48:30.7505801Z ##[debug]at New-PowerBIWorkSpace, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.28\ps_modules\PowerBI\PowerBI.psm1: line 600
2022-03-02T17:48:30.7569194Z ##[debug]at Get-PowerBIGroupPath, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.28\ps_modules\PowerBI\PowerBI.psm1: line 679
2022-03-02T17:48:30.7589268Z ##[debug]at Publish-PowerBIFile, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.28\ps_modules\PowerBI\PowerBI.psm1: line 766
2022-03-02T17:48:30.7609484Z ##[debug]at <ScriptBlock><Process>, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.28\run.ps1: line 104
2022-03-02T17:48:30.7627852Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-03-02T17:48:30.7758688Z ##[debug]at <ScriptBlock>, <No file>: line 22
2022-03-02T17:48:30.7775706Z ##[debug]at <ScriptBlock>, <No file>: line 18
2022-03-02T17:48:30.7796653Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-03-02T17:48:30.7857978Z ##[debug]Exception:

**Comment by maikvandergaag** [comment]
Does the SPN has the appropriate API permissions? Seems like you authentication option is not working correctly

**Comment by tushmesh** [comment]
![image](https://user-images.githubusercontent.com/39365355/156541265-3fbed943-b3da-4d50-ba2d-6938f4bae413.png)

**Comment by maikvandergaag** [comment]
Depending on the actions you want you would arrange the permissions. The pipeline read write permissions is not enough.

**Comment by tushmesh** [comment]
I am trying to publish reports from Azure DevOps to PowerBI. What permissions it is expecting ?

**Comment by tushmesh** [comment]
In my organization they are reluctant to provide the highest level of permission. 
i.e. Tenant.Read.All or Tenant.ReadWrite.All

What will be the steps/workflow and how the permission will work in terms of application and what data will be read/write back to the tenant ?

We are just using this plugin to perform a CI/CD from Azure DevOps to PowerBI workspace.

**Comment by maikvandergaag** [comment]
@tushmesh: Of course, organizations are not keen of giving Tenant Read Write all permissions. This is also not required for the extension. Depending on the actions you want to perform you should give the SPN the correct permissions. 

You do not have to give permissions for all action so If you will be doing only read actions you would have to supply only the read permissions.

**Comment by tushmesh** [comment]
As I am trying "Publish" action hope Tenant.Read.All will suffice.

**Comment by maikvandergaag** [comment]
@tushmesh:

If you just want to publish I think the following should be the absolute minimum. 

- To read the workspaces:
Workspace.Read.All

- To read for existing reports
Report.Read.All

- To import the pbix file:
Dataset.ReadWrite.All

**Comment by tushmesh** [comment]
Required access are in place. But still getting the same error

![image](https://user-images.githubusercontent.com/39365355/158563099-fbf57a1e-4188-4ab3-bd6f-f2d2e55d0084.png)

**Comment by maikvandergaag** [comment]
Could you try adding Report.ReadWrite.All

**Comment by tushmesh** [comment]
[Error_Log.txt](https://github.com/maikvandergaag/msft-extensions/files/8332776/Error_Log.txt)

Even after giving Report.ReadWrite.All, getting the 'Unauthorised' error.

All the .pbix files are under Directory: **D:\a\1\s\PowerBI\reports**, which I am listing in my pipeline to verify the path.

![image](https://user-images.githubusercontent.com/39365355/159695194-e60e22db-4e38-453c-970d-c55c1407cb79.png)

**Comment by tushmesh** [comment]
Hope the permissions are proper .. and can you please elaborate for SPN authorization.


<img width="685" alt="Permissions" src="https://user-images.githubusercontent.com/39365355/161063195-556212ed-3179-41a1-8c50-bdf64688f906.png">

**Comment by Pass1406** [comment]
@tushmesh can you tell by which mode did you create the pipeline, by azure Repos git ..where you create yaml code or by classic editor....?

**Comment by maikvandergaag** [comment]
@tushmesh did you follow this? https://learn.microsoft.com/en-us/power-bi/developer/embedded/embed-service-principal?WT.mc_id=AZ-MVP-5004255

**Comment by tushmesh** [comment]
@zhunipingan 
In our case, Platform team failed to add the Service Principal to the Security Group
