### ISSUE TITLE
A task was cancelled

### ISSUE THREAD

**Issue by omptech** [maikvandergaag/msft-extensions#384]

**Comment by omptech** [comment]
![image](https://user-images.githubusercontent.com/55268151/158603923-1c8aae89-7fb3-4d1e-ad30-e59b52a09825.png)

**Comment by maikvandergaag** [comment]
Could you please add additional information

**Comment by omptech** [comment]
When we publish the reports sometimes it gets published successfully. But sometimes it gets failed and give this error ( A task was cancelled). It is just giving this error only which is not sufficient to understand what is the problem.

**Comment by omptech** [comment]
2022-03-18T20:25:18.0405195Z Trying to publish PowerBI File: D:\a\r1\a\_CIAP-Master\CIAPArtifact\Report\Brokers\Close Opportunity Analysis Report.pbix
2022-03-18T20:25:18.0426892Z Checking for existing Reports with the name: Close Opportunity Analysis Report
2022-03-18T20:25:18.0501415Z ##[debug]8:25:18 PM - New-PowerBIReport begin processing with ParameterSet Workspace.
2022-03-18T20:25:18.0580114Z ##[debug]8:25:18 PM - Cmdlet version: 1.0.896.0
2022-03-18T20:25:22.3483922Z ##[debug]Request Uri: https://***.powerbi.com/v1.0/myorg/groups/b5ddf08e-aef9-444d-8b88-0469d0629204/imports?datasetDisplayName=Close Opportunity Analysis Report&nameConflict=CreateOrOverwrite
2022-03-18T20:25:22.3518725Z ##[debug]Status Code: Accepted (202)
2022-03-18T20:25:22.3548725Z ##[debug]Request Uri: https://***.powerbi.com/v1.0/myorg/groups/b5ddf08e-aef9-444d-8b88-0469d0629204/imports/bb5b79e2-4947-4f96-b228-3f99bedafe35
2022-03-18T20:25:22.3606565Z ##[debug]Status Code: OK (200)
2022-03-18T20:25:22.3689519Z ##[debug]Request Uri: https://***.powerbi.com/v1.0/myorg/groups/b5ddf08e-aef9-444d-8b88-0469d0629204/imports/bb5b79e2-4947-4f96-b228-3f99bedafe35
2022-03-18T20:25:22.3691858Z ##[debug]Status Code: OK (200)
2022-03-18T20:25:22.3747496Z ##[debug]Request Uri: https://***.powerbi.com/v1.0/myorg/groups/b5ddf08e-aef9-444d-8b88-0469d0629204/imports/bb5b79e2-4947-4f96-b228-3f99bedafe35
2022-03-18T20:25:22.3773124Z ##[debug]Status Code: OK (200)
2022-03-18T20:25:22.3802445Z ##[debug]Request Uri: https://***.powerbi.com/v1.0/myorg/groups/b5ddf08e-aef9-444d-8b88-0469d0629204/imports/bb5b79e2-4947-4f96-b228-3f99bedafe35
2022-03-18T20:25:22.3869275Z ##[debug]Status Code: OK (200)
2022-03-18T20:25:22.3917753Z ##[debug]Request Uri: https://***.powerbi.com/v1.0/myorg/groups/b5ddf08e-aef9-444d-8b88-0469d0629204/imports/bb5b79e2-4947-4f96-b228-3f99bedafe35
2022-03-18T20:25:22.3985479Z ##[debug]Status Code: OK (200)
2022-03-18T20:25:22.4012370Z ##[debug]Request Uri: https://***.powerbi.com/v1.0/myorg/groups/b5ddf08e-aef9-444d-8b88-0469d0629204/imports/bb5b79e2-4947-4f96-b228-3f99bedafe35
2022-03-18T20:25:22.4059104Z ##[debug]Status Code: OK (200)
2022-03-18T20:25:22.4134682Z ##[debug]Request Uri: https://***.powerbi.com/v1.0/myorg/groups/b5ddf08e-aef9-444d-8b88-0469d0629204/imports/bb5b79e2-4947-4f96-b228-3f99bedafe35
2022-03-18T20:25:22.4173409Z ##[debug]Status Code: OK (200)
2022-03-18T20:25:22.4243402Z ##[debug]8:25:22 PM - New-PowerBIReport end processing.
2022-03-18T20:25:22.4246883Z ##[debug]Processed: ##vso[task.setvariable variable=PowerBIActions.ReportName]Close Opportunity Analysis Report
2022-03-18T20:25:22.4272450Z Trying to publish PowerBI File: D:\a\r1\a\_CIAP-Master\CIAPArtifact\Report\Brokers\Company Deals to Interaction Time Report Confidential.pbix
2022-03-18T20:25:22.4288909Z Checking for existing Reports with the name: Company Deals to Interaction Time Report Confidential
2022-03-18T20:25:22.4393479Z ##[debug]8:25:22 PM - New-PowerBIReport begin processing with ParameterSet Workspace.
2022-03-18T20:25:22.4458721Z ##[debug]8:25:22 PM - Cmdlet version: 1.0.896.0
2022-03-18T20:27:02.4784225Z Done processing Power BI Actions
2022-03-18T20:27:02.4891178Z ##[debug]Caught exception from task script.
2022-03-18T20:27:02.4945650Z ##[debug]Error record:
2022-03-18T20:27:02.5940888Z ##[debug]New-PowerBIReport : A task was canceled.
2022-03-18T20:27:02.5957296Z ##[debug]At D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.29\ps_modules\PowerBI\PowerBI.psm1:797 char:27
2022-03-18T20:27:02.5982038Z ##[debug]+ ...   $report = New-PowerBIReport -Path $filePath -Name $fileToPublish -W ...
2022-03-18T20:27:02.6001135Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-03-18T20:27:02.6020799Z ##[debug]    + CategoryInfo          : WriteError: (Microsoft.Power...ewPowerBIReport:NewPowerBIReport) [New-PowerBIReport], Ta    skCanceledException
2022-03-18T20:27:02.6070787Z ##[debug]    + FullyQualifiedErrorId : A task was canceled.,Microsoft.PowerBI.Commands.Reports.NewPowerBIReport
2022-03-18T20:27:02.6108697Z ##[debug] 
2022-03-18T20:27:02.6177557Z ##[debug]Script stack trace:
2022-03-18T20:27:02.6222360Z ##[debug]at Publish-PowerBIFile, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.29\ps_modules\PowerBI\PowerBI.psm1: line 797
2022-03-18T20:27:02.6257640Z ##[debug]at <ScriptBlock><Process>, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.29\run.ps1: line 104
2022-03-18T20:27:02.6277981Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-03-18T20:27:02.6305498Z ##[debug]at <ScriptBlock>, <No file>: line 22
2022-03-18T20:27:02.6325925Z ##[debug]at <ScriptBlock>, <No file>: line 18
2022-03-18T20:27:02.6375033Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-03-18T20:27:02.6428915Z ##[debug]Exception:
2022-03-18T20:27:02.6581929Z ##[debug]System.Threading.Tasks.TaskCanceledException: A task was canceled.
2022-03-18T20:27:02.6598561Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2022-03-18T20:27:02.6616680Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-03-18T20:27:02.6642296Z ##[debug]   at Microsoft.PowerBI.Api.V2.Imports.<UploadFile>d__8.MoveNext()
2022-03-18T20:27:02.6677765Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-03-18T20:27:02.6721787Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-03-18T20:27:02.6741949Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2022-03-18T20:27:02.6764814Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-03-18T20:27:02.6781421Z ##[debug]   at Microsoft.PowerBI.Api.V2.Imports.<PostImportFileWithHttpMessage>d__7.MoveNext()
2022-03-18T20:27:02.6811561Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-03-18T20:27:02.6829750Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-03-18T20:27:02.6904561Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2022-03-18T20:27:02.6926940Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-03-18T20:27:02.6953372Z ##[debug]   at Microsoft.PowerBI.Api.V2.ImportsExtensions.PostImportWithFileInGroup(IImports operations, String groupId, Stream fileStream, String datasetDisplayName, String nameConflict, Nullable`1 skipReport)
2022-03-18T20:27:02.6998787Z ##[debug]   at Microsoft.PowerBI.Common.Api.Reports.ReportsClient.PostImportForWorkspace(Guid workspaceId, String datasetDisplayName, String filePath, ImportConflictHandlerModeEnum nameConflict)
2022-03-18T20:27:02.7014495Z ##[debug]   at Microsoft.PowerBI.Common.Api.Reports.ReportsClient.PostReportForWorkspace(Guid workspaceId, String reportName, String filePath, ImportConflictHandlerModeEnum nameConflict, Int32 timeout)
2022-03-18T20:27:02.7034398Z ##[debug]   at Microsoft.PowerBI.Commands.Reports.NewPowerBIReport.ExecuteCmdlet()
2022-03-18T20:27:02.7059196Z ##[debug]   at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
2022-03-18T20:27:02.7385376Z ##[***]A task was canceled.
2022-03-18T20:27:02.7387009Z ##[debug]Processed: ##vso[task.logissue type=***]A task was canceled.
2022-03-18T20:27:02.7403548Z ##[debug]Processed: ##vso[task.complete result=Failed]
2022-03-18T20:27:02.7814492Z ##[section]Finishing: PowerBI Publish Reports to Workspace | Broker

**Comment by maikvandergaag** [comment]
Thanks that gives much more insights. Is it always the same report that fails? Will go through the logs in details on Monday and will let you know

**Comment by omptech** [comment]
No, It does not fails for the same report.

**Comment by maikvandergaag** [comment]
This is because of the resources available on the Power BI side. I now included a timeout to the call this would maybe help. Give it about 30min to be published.

**Comment by omptech** [comment]
Do I need to change anything in my pipeline? Because still it is giving the same error.

**Comment by maikvandergaag** [comment]
No you should not could you send the new log

**Comment by maikvandergaag** [comment]
How large are the reports you try to publish to PowerBI.

The cancellation is happening on the PowerBI side. Seems to be something capacity related. Could you check what is does when publishing in separate tasks?

**Comment by omptech** [comment]
The error we are facing in the report (Message Sentiment Report V2 Confidential.pbix). Its size is 409 MB. 
We are taking source file as **$(ArtifactName)/Report/*.pbix** when publishing the reports. So Do you you want that I should check by publishing single report in separate task like this $(ArtifactName)/Report/name.pbix.

**Comment by maikvandergaag** [comment]
Yes please and are you deploying to a regular workspace or a premium one

**Comment by omptech** [comment]
ok, We are deploying to a regular workspace.

**Comment by omptech** [comment]
I checked with separate task but it is still failing with the same error for the report whose size is 708 MB.

**Comment by maikvandergaag** [comment]
Could you double check the version you are running? And can you confirm that the task takes longer before we tried the adjustment?

**Comment by omptech** [comment]
This is the version of extension we are running
![image](https://user-images.githubusercontent.com/55268151/159850231-8b3a12eb-b1ba-477e-be25-7ac880b89bf3.png)

And in the task we are specifying version like this
![image](https://user-images.githubusercontent.com/55268151/159850481-95fab989-28ff-4bc9-b008-bd6ff6789845.png)

**Comment by omptech** [comment]
Today I again checked with separate task but now getting some different error that is The operation has timed out.
2022-03-24T06:01:30.1056052Z Trying to publish PowerBI File: D:\a\r1\a\_CIAP-Master\CIAPArtifact\Report\Managers\Channel Activity Report Confidential.pbix
2022-03-24T06:01:30.1093464Z Checking for existing Reports with the name: Channel Activity Report Confidential
2022-03-24T06:01:30.1174003Z ##[debug]6:01:30 AM - New-PowerBIReport begin processing with ParameterSet Workspace.
2022-03-24T06:01:30.1333309Z ##[debug]6:01:30 AM - Cmdlet version: 1.0.896.0
2022-03-24T06:03:46.2289050Z Done processing Power BI Actions
2022-03-24T06:03:46.2920387Z ##[debug]Caught exception from task script.
2022-03-24T06:03:46.2948863Z ##[debug]Error record:
2022-03-24T06:03:46.3564593Z ##[debug]New-PowerBIReport : The operation has timed out.
2022-03-24T06:03:46.3578186Z ##[debug]At D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.30\ps_modules\PowerBI\PowerBI.psm1:797 char:27
2022-03-24T06:03:46.3589029Z ##[debug]+ ...   $report = New-PowerBIReport -Path $filePath -Name $fileToPublish -W ...
2022-03-24T06:03:46.3601182Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-03-24T06:03:46.3612378Z ##[debug]    + CategoryInfo          : WriteError: (Microsoft.Power...ewPowerBIReport:NewPowerBIReport) [New-PowerBIReport], Ti    meoutException
2022-03-24T06:03:46.3624553Z ##[debug]    + FullyQualifiedErrorId : The operation has timed out.,Microsoft.PowerBI.Commands.Reports.NewPowerBIReport
2022-03-24T06:03:46.3635176Z ##[debug] 
2022-03-24T06:03:46.3653484Z ##[debug]Script stack trace:
2022-03-24T06:03:46.3685116Z ##[debug]at Publish-PowerBIFile, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.30\ps_modules\PowerBI\PowerBI.psm1: line 797
2022-03-24T06:03:46.3696340Z ##[debug]at <ScriptBlock><Process>, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.30\run.ps1: line 104
2022-03-24T06:03:46.3706929Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-03-24T06:03:46.3724207Z ##[debug]at <ScriptBlock>, <No file>: line 22
2022-03-24T06:03:46.3730016Z ##[debug]at <ScriptBlock>, <No file>: line 18
2022-03-24T06:03:46.3740921Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-03-24T06:03:46.3757328Z ##[debug]Exception:
2022-03-24T06:03:46.3833280Z ##[debug]System.TimeoutException: The operation has timed out.
2022-03-24T06:03:46.3844494Z ##[debug]   at Microsoft.PowerBI.Common.Api.Reports.ReportsClient.PostReportForWorkspace(Guid workspaceId, String reportName, String filePath, ImportConflictHandlerModeEnum nameConflict, Int32 timeout)
2022-03-24T06:03:46.3855393Z ##[debug]   at Microsoft.PowerBI.Commands.Reports.NewPowerBIReport.ExecuteCmdlet()
2022-03-24T06:03:46.3866410Z ##[debug]   at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
2022-03-24T06:03:46.4076291Z ##[***]The operation has timed out.
2022-03-24T06:03:46.4078065Z ##[debug]Processed: ##vso[task.logissue type=***]The operation has timed out.
2022-03-24T06:03:46.4086756Z ##[debug]Processed: ##vso[task.complete result=Failed]
2022-03-24T06:03:46.4337523Z ##[section]Finishing: PowerBI Publish Reports to Workspace | Manager-5

**Comment by omptech** [comment]
Hi @maikvandergaag can you please suggest what to do to solve this problem?

**Comment by maikvandergaag** [comment]
Issue seems to be there because of the large set of data. The issue is not caused by the extension it self but by the API. Over the weekend I have updated the extension and the modules within and also increased the timeout again.

Could you try this? Version should now be 5.4.31

**Comment by omptech** [comment]
thanks @maikvandergaag  I tried again but Got the same error. Task was cancelled

2022-03-28T11:57:47.9024725Z ##[debug]11:57:47 AM - New-PowerBIReport begin processing with ParameterSet Workspace.
2022-03-28T11:57:47.9076375Z ##[debug]11:57:47 AM - Cmdlet version: 1.2.1077.0
2022-03-28T11:57:47.9088344Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [03/28/2022 11:57:47] Found 0 cache accounts and 0 broker accounts
2022-03-28T11:57:47.9141701Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [03/28/2022 11:57:47 - 1504f80d-e560-4bc2-b487-8d3330a7e5d7] MSAL MSAL.Desktop with assembly version '4.25.0.0'. CorrelationId(1504f80d-e560-4bc2-b487-8d3330a7e5d7)
2022-03-28T11:57:47.9177003Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [03/28/2022 11:57:47 - 1504f80d-e560-4bc2-b487-8d3330a7e5d7] === AcquireTokenForClientParameters ===
2022-03-28T11:57:47.9204746Z ##[debug]SendX5C: False
2022-03-28T11:57:47.9234006Z ##[debug]WithAzureRegion: False
2022-03-28T11:57:47.9284431Z ##[debug]RegionToUse: 
2022-03-28T11:57:47.9354625Z ##[debug]ForceRefresh: False
2022-03-28T11:57:47.9393160Z ##[debug]
2022-03-28T11:57:47.9465614Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [03/28/2022 11:57:47 - 1504f80d-e560-4bc2-b487-8d3330a7e5d7] 
2022-03-28T11:57:47.9522905Z ##[debug]=== Request Data ===
2022-03-28T11:57:47.9557929Z ##[debug]Authority Provided? - True
2022-03-28T11:57:47.9593098Z ##[debug]Scopes - https://analysis.windows.net/powerbi/***/.default
2022-03-28T11:57:47.9659822Z ##[debug]Extra Query Params Keys (space separated) - 
2022-03-28T11:57:47.9701714Z ##[debug]ApiId - AcquireTokenForClient
2022-03-28T11:57:47.9762115Z ##[debug]IsConfidentialClient - True
2022-03-28T11:57:47.9881669Z ##[debug]SendX5C - False
2022-03-28T11:57:48.0001858Z ##[debug]LoginHint ? False
2022-03-28T11:57:48.0015268Z ##[debug]IsBrokerConfigured - False
2022-03-28T11:57:48.0046052Z ##[debug]HomeAccountId - False
2022-03-28T11:57:48.0181711Z ##[debug]CorrelationId - 1504f80d-e560-4bc2-b487-8d3330a7e5d7
2022-03-28T11:57:48.0210008Z ##[debug]
2022-03-28T11:57:48.0250648Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [03/28/2022 11:57:48 - 1504f80d-e560-4bc2-b487-8d3330a7e5d7] === Token Acquisition (ClientCredentialRequest) started:
2022-03-28T11:57:48.0336697Z ##[debug]	
2022-03-28T11:57:48.0350863Z ##[debug]	Authority Host: login.microsoftonline.com
2022-03-28T11:57:48.0445212Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [03/28/2022 11:57:48 - 1504f80d-e560-4bc2-b487-8d3330a7e5d7] Access token is not expired. Returning the found cache entry. [Current time (03/28/2022 11:57:48) - Expiration Time (03/28/2022 12:56:17 +00:00) - Extended Expiration Time (03/28/2022 12:56:17 +00:00)]
2022-03-28T11:57:48.0483009Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [03/28/2022 11:57:48 - 1504f80d-e560-4bc2-b487-8d3330a7e5d7] === Token Acquisition finished successfully. An access token was returned with Expiration Time: 03/28/2022 12:56:17 +00:00 ===
2022-03-28T11:59:28.1792231Z Done processing Power BI Actions
2022-03-28T11:59:28.2547271Z ##[debug]Caught exception from task script.
2022-03-28T11:59:28.2639349Z ##[debug]Error record:
2022-03-28T11:59:28.3713348Z ##[debug]New-PowerBIReport : A task was canceled.
2022-03-28T11:59:28.3747283Z ##[debug]At D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.31\ps_modules\PowerBI\PowerBI.psm1:797 char:27
2022-03-28T11:59:28.3780556Z ##[debug]+ ...   $report = New-PowerBIReport -Path $filePath -Name $fileToPublish -W ...
2022-03-28T11:59:28.3816323Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-03-28T11:59:28.3852759Z ##[debug]    + CategoryInfo          : WriteError: (Microsoft.Power...ewPowerBIReport:NewPowerBIReport) [New-PowerBIReport], Ta    skCanceledException
2022-03-28T11:59:28.3882251Z ##[debug]    + FullyQualifiedErrorId : A task was canceled.,Microsoft.PowerBI.Commands.Reports.NewPowerBIReport
2022-03-28T11:59:28.4074299Z ##[debug] 
2022-03-28T11:59:28.4112506Z ##[debug]Script stack trace:
2022-03-28T11:59:28.4200195Z ##[debug]at Publish-PowerBIFile, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.31\ps_modules\PowerBI\PowerBI.psm1: line 797
2022-03-28T11:59:28.4284027Z ##[debug]at <ScriptBlock><Process>, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.31\run.ps1: line 104
2022-03-28T11:59:28.4287604Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-03-28T11:59:28.4340743Z ##[debug]at <ScriptBlock>, <No file>: line 22
2022-03-28T11:59:28.4371170Z ##[debug]at <ScriptBlock>, <No file>: line 18
2022-03-28T11:59:28.4457634Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-03-28T11:59:28.4527824Z ##[debug]Exception:
2022-03-28T11:59:28.4881642Z ##[debug]System.Threading.Tasks.TaskCanceledException: A task was canceled.
2022-03-28T11:59:28.4907544Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2022-03-28T11:59:28.4934635Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-03-28T11:59:28.4965116Z ##[debug]   at Microsoft.PowerBI.Api.V2.Imports.<UploadFile>d__8.MoveNext()
2022-03-28T11:59:28.5088124Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-03-28T11:59:28.5116126Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-03-28T11:59:28.5147890Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2022-03-28T11:59:28.5253788Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-03-28T11:59:28.5288008Z ##[debug]   at Microsoft.PowerBI.Api.V2.Imports.<PostImportFileWithHttpMessage>d__7.MoveNext()
2022-03-28T11:59:28.5352556Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-03-28T11:59:28.5380389Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-03-28T11:59:28.5482815Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2022-03-28T11:59:28.5511711Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-03-28T11:59:28.5547588Z ##[debug]   at Microsoft.PowerBI.Api.V2.ImportsExtensions.PostImportWithFileInGroup(IImports operations, String groupId, Stream fileStream, String datasetDisplayName, String nameConflict, Nullable`1 skipReport)
2022-03-28T11:59:28.5615713Z ##[debug]   at Microsoft.PowerBI.Common.Api.Reports.ReportsClient.PostImportForWorkspace(Guid workspaceId, String datasetDisplayName, String filePath, ImportConflictHandlerModeEnum nameConflict)
2022-03-28T11:59:28.5661315Z ##[debug]   at Microsoft.PowerBI.Common.Api.Reports.ReportsClient.PostReportForWorkspace(Guid workspaceId, String reportName, String filePath, ImportConflictHandlerModeEnum nameConflict, Int32 timeout)
2022-03-28T11:59:28.5696081Z ##[debug]   at Microsoft.PowerBI.Commands.Reports.NewPowerBIReport.ExecuteCmdlet()
2022-03-28T11:59:28.5738486Z ##[debug]   at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
2022-03-28T11:59:28.6278272Z ##[***]A task was canceled.
2022-03-28T11:59:28.6280212Z ##[debug]Processed: ##vso[task.logissue type=***]A task was canceled.
2022-03-28T11:59:28.6306668Z ##[debug]Processed: ##vso[task.complete result=Failed]

**Comment by maikvandergaag** [comment]
What kind of agent are you using a Microsoft hosted one?

**Comment by omptech** [comment]
yes, I am using Microsoft hosted one.

**Comment by maikvandergaag** [comment]
Do you have the sam experience when you use the Power BI PowerShell Module?

**Comment by omptech** [comment]
I have the same experience with powrershell module as well

**Comment by ManuelWernerbtelligent** [comment]
Same issue here with the "A task was cancelled" Error

**Comment by ManuelWernerbtelligent** [comment]
When I publish the reports I got this error "A task was cancelled" after exactly 100 seconds. 
Is there any timeout? 

![image](https://user-images.githubusercontent.com/104978878/196166362-de1053e1-e8a9-450f-b28d-a95a271e0c59.png)
