### ISSUE TITLE
PowerBIActions - One or more errors occurred - Error Acquiring Token

### ISSUE THREAD

**Issue by DustinBryant** [maikvandergaag/msft-extensions#391]
**Describe the issue**
When using Publish task it fails to get a token

**Extension **
 - Extension: Power BI Actions
 - Version: 5.4.31

**Situation (please complete the following information):**

 - Agent type: Self hosted agent
 - Autentication: UsernamePassword
 - Extension Version: 5.4.31

**Log info**
Please add the log file of the agent in debug mode [Add the variable system.debug with the value 'true ' to your pipeline]
```
##[debug]INPUT_POWERBISERVICEENDPOINT: '2291247f-fe03-4223-bbd7-18b22bd1418f'
##[debug]ENDPOINT_URL_2291247f-fe03-4223-bbd7-18b22bd1418f: 'https://api.powerbi.com/v1.0/myorg'
##[debug]ENDPOINT_AUTH_2291247f-fe03-4223-bbd7-18b22bd1418f: '********'
##[debug]ENDPOINT_DATA_2291247f-fe03-4223-bbd7-18b22bd1418f: '{"OrganizationType":"Public"}'
##[debug]{
##[debug]    "Url":  "https://api.powerbi.com/v1.0/myorg",
##[debug]    "Data":  {
##[debug]                 "OrganizationType":  "Public"
##[debug]             },
##[debug]    "Auth":  {
##[debug]                 "parameters":  {
##[debug]                                    "username":  "***",
##[debug]                                    "password":  ***
##[debug]                                },
##[debug]                 "scheme":  "UsernamePassword"
##[debug]             }
##[debug]}
##[debug]5:42:30 PM - Connect-PowerBIServiceAccount begin processing with ParameterSet UserAndCredential.
##[debug]5:42:30 PM - Cmdlet version: 1.2.1077.0
##[debug]Updated Azure AD authority with /organizations endpoint, new value: https://login.microsoftonline.com/organizations
##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.14393.0 [04/07/2022 00:42:31] Found 0 cache accounts and 0 broker accounts
##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.14393.0 [04/07/2022 00:42:31 - f9dee341-a7fe-4c91-839f-2ab8bcc0dee3] MSAL MSAL.Desktop with assembly version '4.25.0.0'. CorrelationId(f9dee341-a7fe-4c91-839f-2ab8bcc0dee3)
##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.14393.0 [04/07/2022 00:42:31 - f9dee341-a7fe-4c91-839f-2ab8bcc0dee3] 
##[debug]=== Request Data ===
##[debug]Authority Provided? - True
##[debug]Scopes - https://analysis.windows.net/powerbi/api/.default
##[debug]Extra Query Params Keys (space separated) - 
##[debug]ApiId - AcquireTokenByUsernamePassword
##[debug]IsConfidentialClient - False
##[debug]SendX5C - False
##[debug]LoginHint ? False
##[debug]IsBrokerConfigured - False
##[debug]HomeAccountId - False
##[debug]CorrelationId - f9dee341-a7fe-4c91-839f-2ab8bcc0dee3
##[debug]
##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.14393.0 [04/07/2022 00:42:31 - f9dee341-a7fe-4c91-839f-2ab8bcc0dee3] === Token Acquisition (UsernamePasswordRequest) started:
##[debug]
##[debug]	Authority Host: login.microsoftonline.com
##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.14393.0 [04/07/2022 00:42:31 - f9dee341-a7fe-4c91-839f-2ab8bcc0dee3] Fetching instance discovery from the network from host login.microsoftonline.com. 
Done processing Power BI Actions
##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]Connect-PowerBIServiceAccount : One or more errors occurred.
##[debug]At C:\DevOpsAgent-01\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.31\run.ps1:34 char:4
##[debug]+             Connect-PowerBIServiceAccount -Environment $organizationT ...
##[debug]+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : WriteError: (Microsoft.Power...IServiceAccount:ConnectPowerBIServiceAccount) [Connect-Po    werBIServiceAccount], AggregateException
##[debug]    + FullyQualifiedErrorId : One or more errors occurred.,Microsoft.PowerBI.Commands.Profile.ConnectPowerBIServiceAcc    ount
##[debug] 
##[debug]Script stack trace:
##[debug]at <ScriptBlock><Process>, C:\DevOpsAgent-01\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.31\run.ps1: line 34
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.AggregateException: One or more errors occurred. ---> System.Security.Authentication.AuthenticationException: Error Acquiring Token:
##[debug]An error occurred while sending the request.
##[debug]   at Microsoft.PowerBI.Common.Authentication.WindowsAuthenticationFactory.<HandleAuthentication>d__3.MoveNext()
##[debug]--- End of stack trace from previous location where exception was thrown ---
##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
##[debug]   at Microsoft.PowerBI.Common.Authentication.WindowsAuthenticationFactory.<Authenticate>d__2.MoveNext()
##[debug]--- End of stack trace from previous location where exception was thrown ---
##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
##[debug]   at Microsoft.PowerBI.Commands.Common.AuthenticationFactorySelector.<Authenticate>d__6.MoveNext()
##[debug]   --- End of inner exception stack trace ---
##[debug]   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
##[debug]   at Microsoft.PowerBI.Commands.Profile.ConnectPowerBIServiceAccount.ExecuteCmdlet()
##[debug]   at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
##[debug]---> (Inner Exception #0) System.Security.Authentication.AuthenticationException: Error Acquiring Token:
##[debug]An error occurred while sending the request.
##[debug]   at Microsoft.PowerBI.Common.Authentication.WindowsAuthenticationFactory.<HandleAuthentication>d__3.MoveNext()
##[debug]--- End of stack trace from previous location where exception was thrown ---
##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
##[debug]   at Microsoft.PowerBI.Common.Authentication.WindowsAuthenticationFactory.<Authenticate>d__2.MoveNext()
##[debug]--- End of stack trace from previous location where exception was thrown ---
##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
##[debug]   at Microsoft.PowerBI.Commands.Common.AuthenticationFactorySelector.<Authenticate>d__6.MoveNext()<---
##[debug]
##[error]One or more errors occurred.
##[debug]Processed: ##vso[task.logissue type=error]One or more errors occurred.
##[debug]Processed: ##vso[task.complete result=Failed]
```

**Additional information**
This used to work which made me believe maybe the account password was changed.  It's also been a couple months since needing to run the pipeline.  I modified the service connection and put in the latest password but the issue continues to occur.  I logged into the account on Power BI to make sure it still had admin rights to the workspace and it did.

**Comment by maikvandergaag** [comment]
Hi Dustin,

I will look into the issue. It could maybe also be related to the update of the module. A few questions:
- What kind of agent are you using?
- Does this account fall under conditional access rules in AAD?
- Do you have ADFS configured in between?
- Do you have MFA configured for the account?

**Comment by maikvandergaag** [comment]
Is it possible to try it on a Microsoft Hosted Agent

**Comment by DustinBryant** [comment]
I changed it over to use the Microsoft Hosted agent and it worked.  This leads me to believe it's a proxy issue on our end.  Thank you for your help.
