### ISSUE TITLE
Operation returned an invalid status code 'Unauthorized'

### ISSUE THREAD

**Issue by yorickbouma** [maikvandergaag/msft-extensions#409]
We are experiencing issues with the Upload Power BI report actions. We are using a Power BI Premium Reserved/Dedicated Capacity.

We have done the following:
1. Created a SPN and assigned API permissions
![image](https://user-images.githubusercontent.com/49064748/171219327-1fa735c3-da9c-4377-b9c3-ba678fb6e997.png)
2. Added SPN as Admin to Workspace
![image](https://user-images.githubusercontent.com/49064748/171220419-d38400f6-6937-452c-a50c-be9859aee58a.png)
3. Added SPN as Power BI Service Connection in DevOps
![image](https://user-images.githubusercontent.com/49064748/171220195-ef517b7f-dc90-486e-a77b-56a14a4d6be6.png)
4. Added a step to publish a report
![image](https://user-images.githubusercontent.com/49064748/171220692-ebd10f25-d096-40f8-b96a-f99aef8d0749.png)

Then we are receiving the error: ##[error]Operation returned an invalid status code 'Unauthorized'

This is the full log:
`2022-05-31T15:51:24.8325667Z ##[debug]INPUT_POWERBISERVICEENDPOINT: '71120b8d-e1a3-411a-9d40-e79cb801f70a'
2022-05-31T15:51:24.8483894Z ##[debug]ENDPOINT_URL_71120b8d-e1a3-411a-9d40-e79cb801f70a: 'https://api.powerbi.com/v1.0/myorg'
2022-05-31T15:51:24.8507329Z ##[debug]ENDPOINT_AUTH_71120b8d-e1a3-411a-9d40-e79cb801f70a: '********'
2022-05-31T15:51:24.8534802Z ##[debug]ENDPOINT_DATA_71120b8d-e1a3-411a-9d40-e79cb801f70a: '{"OrganizationType":"Public"}'
2022-05-31T15:51:24.9563696Z ##[debug]{
2022-05-31T15:51:24.9585038Z ##[debug]    "Url":  "https://api.powerbi.com/v1.0/myorg",
2022-05-31T15:51:24.9597951Z ##[debug]    "Data":  {
2022-05-31T15:51:24.9610549Z ##[debug]                 "OrganizationType":  "Public"
2022-05-31T15:51:24.9624851Z ##[debug]             },
2022-05-31T15:51:24.9637994Z ##[debug]    "Auth":  {
2022-05-31T15:51:24.9650439Z ##[debug]                 "parameters":  {
2022-05-31T15:51:24.9663451Z ##[debug]                                    "TenantId":  "66e85***",
2022-05-31T15:51:24.9676391Z ##[debug]                                    "ClientId":  "***",
2022-05-31T15:51:24.9689605Z ##[debug]                                    "ClientSecret":  ***,
2022-05-31T15:51:24.9708937Z ##[debug]                                    "ClientCertificate":  "Bag Attributes     Microsoft Local Key set: \u003cNo Values\u003e     localKeyID: 01 00 00 00      friendlyName: te-b1226e24-551c-47f8-832b-0781896cfa79     Microsoft CSP Name: Microsoft Software Key Storage Provider Key Attributes     X509v3 Key Usage: 90  -----BEGIN PRIVATE KEY----- ***-----END CERTIFICATE-----"
2022-05-31T15:51:24.9718497Z ##[debug]                                },
2022-05-31T15:51:24.9727245Z ##[debug]                 "scheme":  "None"
2022-05-31T15:51:24.9739739Z ##[debug]             }
2022-05-31T15:51:24.9752273Z ##[debug]}
2022-05-31T15:51:25.7195989Z ##[debug]3:51:25 PM - Connect-PowerBIServiceAccount begin processing with ParameterSet ServicePrincipal.
2022-05-31T15:51:25.7223388Z ##[debug]3:51:25 PM - Cmdlet version: 1.2.1077.0
2022-05-31T15:51:25.7500047Z ##[debug]Updated Azure AD authority with -Tenant specified, new value: https://login.microsoftonline.com/66e853de-ece3-44dd-9d66-ee6bdf4159d4
2022-05-31T15:51:25.9266234Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [05/31/2022 15:51:25] Found 0 cache accounts and 0 broker accounts
2022-05-31T15:51:25.9381617Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [05/31/2022 15:51:25 - 359d04af-5a0d-40d7-b9a5-fafd52a5f642] MSAL MSAL.Desktop with assembly version '4.25.0.0'. CorrelationId(359d04af-5a0d-40d7-b9a5-fafd52a5f642)
2022-05-31T15:51:25.9406225Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [05/31/2022 15:51:25 - 359d04af-5a0d-40d7-b9a5-fafd52a5f642] === AcquireTokenForClientParameters ===
2022-05-31T15:51:25.9411616Z ##[debug]SendX5C: False
2022-05-31T15:51:25.9434817Z ##[debug]WithAzureRegion: False
2022-05-31T15:51:25.9448124Z ##[debug]RegionToUse: 
2022-05-31T15:51:25.9461459Z ##[debug]ForceRefresh: False
2022-05-31T15:51:25.9464240Z ##[debug]
2022-05-31T15:51:25.9621940Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [05/31/2022 15:51:25 - 359d04af-5a0d-40d7-b9a5-fafd52a5f642] 
2022-05-31T15:51:25.9635322Z ##[debug]=== Request Data ===
2022-05-31T15:51:25.9648721Z ##[debug]Authority Provided? - True
2022-05-31T15:51:25.9662398Z ##[debug]Scopes - https://analysis.windows.net/powerbi/api/.default
2022-05-31T15:51:25.9675173Z ##[debug]Extra Query Params Keys (space separated) - 
2022-05-31T15:51:25.9688059Z ##[debug]ApiId - AcquireTokenForClient
2022-05-31T15:51:25.9700586Z ##[debug]IsConfidentialClient - True
2022-05-31T15:51:25.9713126Z ##[debug]SendX5C - False
2022-05-31T15:51:25.9725556Z ##[debug]LoginHint ? False
2022-05-31T15:51:25.9739678Z ##[debug]IsBrokerConfigured - False
2022-05-31T15:51:25.9754517Z ##[debug]HomeAccountId - False
2022-05-31T15:51:25.9759424Z ##[debug]CorrelationId - 359d04af-5a0d-40d7-b9a5-fafd52a5f642
2022-05-31T15:51:25.9771439Z ##[debug]
2022-05-31T15:51:25.9809914Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [05/31/2022 15:51:25 - 359d04af-5a0d-40d7-b9a5-fafd52a5f642] === Token Acquisition (ClientCredentialRequest) started:
2022-05-31T15:51:25.9825317Z ##[debug]	
2022-05-31T15:51:25.9867258Z ##[debug]	Authority Host: login.microsoftonline.com
2022-05-31T15:51:26.0319076Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [05/31/2022 15:51:26 - 359d04af-5a0d-40d7-b9a5-fafd52a5f642] Fetching instance discovery from the network from host login.microsoftonline.com. 
2022-05-31T15:51:26.5299249Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [05/31/2022 15:51:26 - 359d04af-5a0d-40d7-b9a5-fafd52a5f642] Resolving authority endpoints... Already resolved? - FALSE
2022-05-31T15:51:26.5315448Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [05/31/2022 15:51:26 - 359d04af-5a0d-40d7-b9a5-fafd52a5f642] ScopeSet was missing from the token response, so using developer provided scopes in the result. 
2022-05-31T15:51:26.5335624Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [05/31/2022 15:51:26 - 359d04af-5a0d-40d7-b9a5-fafd52a5f642] Checking client info returned from the server..
2022-05-31T15:51:26.5341039Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [05/31/2022 15:51:26 - 359d04af-5a0d-40d7-b9a5-fafd52a5f642] Saving Token Response to cache..
2022-05-31T15:51:26.5439280Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [05/31/2022 15:51:26 - 359d04af-5a0d-40d7-b9a5-fafd52a5f642] ID Token not present in response. 
2022-05-31T15:51:26.5447861Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [05/31/2022 15:51:26 - 359d04af-5a0d-40d7-b9a5-fafd52a5f642] Saving AT in cache and removing overlapping ATs...
2022-05-31T15:51:26.5454768Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [05/31/2022 15:51:26 - 359d04af-5a0d-40d7-b9a5-fafd52a5f642] Looking for scopes for the authority in the cache which intersect with https://analysis.windows.net/powerbi/api/.default
2022-05-31T15:51:26.5485439Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [05/31/2022 15:51:26 - 359d04af-5a0d-40d7-b9a5-fafd52a5f642] Intersecting scope entries count - 0
2022-05-31T15:51:26.5507859Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [05/31/2022 15:51:26 - 359d04af-5a0d-40d7-b9a5-fafd52a5f642] === Token Acquisition finished successfully. An access token was returned with Expiration Time: 05/31/2022 16:51:25 +00:00 ===
2022-05-31T15:51:26.5522019Z ##[debug]3:51:26 PM - Connect-PowerBIServiceAccount end processing.
2022-05-31T15:51:26.5544751Z ##[debug]INPUT_POWERBIPATH: 'D:\a\1\s\Afname Statistiek.rdl'
2022-05-31T15:51:26.5575498Z ##[debug]INPUT_WORKSPACENAME: 'HNLTestWorkspace'
2022-05-31T15:51:26.5635374Z ##[debug]INPUT_OVERWRITE: 'true'
2022-05-31T15:51:26.5636962Z ##[debug] Converted to bool: True
2022-05-31T15:51:26.5643064Z ##[debug]INPUT_CREATE: 'false'
2022-05-31T15:51:26.5659081Z ##[debug] Converted to bool: False
2022-05-31T15:51:26.5687977Z ##[debug]INPUT_ACTION: 'Publish'
2022-05-31T15:51:26.5726995Z ##[debug]INPUT_DATASETNAME (empty)
2022-05-31T15:51:26.5760745Z ##[debug]INPUT_OLDURL (empty)
2022-05-31T15:51:26.5800068Z ##[debug]INPUT_NEWURL (empty)
2022-05-31T15:51:26.5822071Z ##[debug]INPUT_OLDSERVER (empty)
2022-05-31T15:51:26.5829177Z ##[debug]INPUT_NEWSERVER (empty)
2022-05-31T15:51:26.5855277Z ##[debug]INPUT_OLDDATABASE (empty)
2022-05-31T15:51:26.5893183Z ##[debug]INPUT_GROUPOBJECTIDS (empty)
2022-05-31T15:51:26.5907951Z ##[debug]INPUT_NEWDATABASE (empty)
2022-05-31T15:51:26.5958047Z ##[debug]INPUT_PERMISSION (empty)
2022-05-31T15:51:26.5959463Z ##[debug]INPUT_USERS (empty)
2022-05-31T15:51:26.5984291Z ##[debug]INPUT_DATASOURCETYPE: 'Sql'
2022-05-31T15:51:26.6002633Z ##[debug]INPUT_UPDATEALL: 'false'
2022-05-31T15:51:26.6022555Z ##[debug] Converted to bool: False
2022-05-31T15:51:26.6028416Z ##[debug]INPUT_SKIPREPORT: 'false'
2022-05-31T15:51:26.6049973Z ##[debug] Converted to bool: False
2022-05-31T15:51:26.6070995Z ##[debug]INPUT_INDIVIDUAL (empty)
2022-05-31T15:51:26.6108407Z ##[debug]INPUT_SERVICEPRINCIPALS (empty)
2022-05-31T15:51:26.6120329Z ##[debug]INPUT_CONNECTIONSTRING (empty)
2022-05-31T15:51:26.6219217Z ##[debug]INPUT_PARAMETERINPUT (empty)
2022-05-31T15:51:26.6220645Z ##[debug]INPUT_GATEWAYNAME (empty)
2022-05-31T15:51:26.6723291Z ##[debug]INPUT_REPORTNAME (empty)
2022-05-31T15:51:26.6767845Z ##[debug]INPUT_CAPACITYNAME: 'LIT-HNL-P1-Analytics'
2022-05-31T15:51:26.6769359Z ##[debug]INPUT_USERNAME (empty)
2022-05-31T15:51:26.6777191Z ##[debug]INPUT_PASSWORD (empty)
2022-05-31T15:51:26.6831374Z ##[debug]INPUT_REFRESHSCHEDULEINPUT (empty)
2022-05-31T15:51:26.7562616Z ##[debug]INPUT_CROSSWORKSPACEREBINDING: 'false'
2022-05-31T15:51:26.7593220Z ##[debug] Converted to bool: False
2022-05-31T15:51:26.7618105Z ##[debug]INPUT_REPORTWORKSPACENAME (empty)
2022-05-31T15:51:26.7647463Z ##[debug]INPUT_TABULAREDITORARGUMENTS (empty)
2022-05-31T15:51:26.7665852Z ##[debug]WorkspaceName         : HNLTestWorkspace
2022-05-31T15:51:26.7684778Z ##[debug]Create                : False
2022-05-31T15:51:26.7697228Z ##[debug]File patern             : D:\a\1\s\Afname Statistiek.rdl
2022-05-31T15:51:26.7723157Z ##[debug]Remove report           : False
2022-05-31T15:51:26.7904643Z Getting Power BI Workspace properties; HNLTestWorkspace
2022-05-31T15:51:26.8065311Z ##[debug]3:51:26 PM - Get-PowerBIWorkspace begin processing with ParameterSet Name.
2022-05-31T15:51:26.8073883Z ##[debug]3:51:26 PM - Cmdlet version: 1.2.1077.0
2022-05-31T15:51:26.8561518Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [05/31/2022 15:51:26] Found 0 cache accounts and 0 broker accounts
2022-05-31T15:51:26.8599526Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [05/31/2022 15:51:26 - 72aa719b-ed39-4924-b3b7-366fb7fa44bf] MSAL MSAL.Desktop with assembly version '4.25.0.0'. CorrelationId(72aa719b-ed39-4924-b3b7-366fb7fa44bf)
2022-05-31T15:51:26.8613856Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [05/31/2022 15:51:26 - 72aa719b-ed39-4924-b3b7-366fb7fa44bf] === AcquireTokenForClientParameters ===
2022-05-31T15:51:26.8628236Z ##[debug]SendX5C: False
2022-05-31T15:51:26.8640942Z ##[debug]WithAzureRegion: False
2022-05-31T15:51:26.8653598Z ##[debug]RegionToUse: 
2022-05-31T15:51:26.8666008Z ##[debug]ForceRefresh: False
2022-05-31T15:51:26.8692034Z ##[debug]
2022-05-31T15:51:26.8705698Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [05/31/2022 15:51:26 - 72aa719b-ed39-4924-b3b7-366fb7fa44bf] 
2022-05-31T15:51:26.8719089Z ##[debug]=== Request Data ===
2022-05-31T15:51:26.8731826Z ##[debug]Authority Provided? - True
2022-05-31T15:51:26.8746853Z ##[debug]Scopes - https://analysis.windows.net/powerbi/api/.default
2022-05-31T15:51:26.8760598Z ##[debug]Extra Query Params Keys (space separated) - 
2022-05-31T15:51:26.8766104Z ##[debug]ApiId - AcquireTokenForClient
2022-05-31T15:51:26.8782096Z ##[debug]IsConfidentialClient - True
2022-05-31T15:51:26.8815058Z ##[debug]SendX5C - False
2022-05-31T15:51:26.8815833Z ##[debug]LoginHint ? False
2022-05-31T15:51:26.8819051Z ##[debug]IsBrokerConfigured - False
2022-05-31T15:51:26.8839867Z ##[debug]HomeAccountId - False
2022-05-31T15:51:26.8857764Z ##[debug]CorrelationId - 72aa719b-ed39-4924-b3b7-366fb7fa44bf
2022-05-31T15:51:26.8906628Z ##[debug]
2022-05-31T15:51:26.8937578Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [05/31/2022 15:51:26 - 72aa719b-ed39-4924-b3b7-366fb7fa44bf] === Token Acquisition (ClientCredentialRequest) started:
2022-05-31T15:51:26.8942366Z ##[debug]	
2022-05-31T15:51:26.9005993Z ##[debug]	Authority Host: login.microsoftonline.com
2022-05-31T15:51:26.9033922Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [05/31/2022 15:51:26 - 72aa719b-ed39-4924-b3b7-366fb7fa44bf] Access token is not expired. Returning the found cache entry. [Current time (05/31/2022 15:51:26) - Expiration Time (05/31/2022 16:51:25 +00:00) - Extended Expiration Time (05/31/2022 16:51:25 +00:00)]
2022-05-31T15:51:26.9039246Z ##[debug](False) MSAL 4.25.0.0 MSAL.Desktop Microsoft Windows NT 10.0.20348.0 [05/31/2022 15:51:26 - 72aa719b-ed39-4924-b3b7-366fb7fa44bf] === Token Acquisition finished successfully. An access token was returned with Expiration Time: 05/31/2022 16:51:25 +00:00 ===
2022-05-31T15:51:27.7191403Z ##[debug]Error record:
2022-05-31T15:51:27.7871913Z ##[debug]Get-PowerBIWorkspace : Operation returned an invalid status code 'Unauthorized'
2022-05-31T15:51:27.7883529Z ##[debug]At D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.33\ps_modules\PowerBI\PowerBI.psm1:676 char:22
2022-05-31T15:51:27.7896781Z ##[debug]+ ...       $workspace = Get-PowerBIWorkspace -Name $WorkspaceName -Verbose
2022-05-31T15:51:27.7901736Z ##[debug]+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-05-31T15:51:27.7914338Z ##[debug]    + CategoryInfo          : WriteError: (Microsoft.Power...owerBIWorkspace:GetPowerBIWorkspace) [Get-PowerBIWorkspac    e], HttpOperationException
2022-05-31T15:51:27.7926837Z ##[debug]    + FullyQualifiedErrorId : Operation returned an invalid status code 'Unauthorized',Microsoft.PowerBI.Commands.Work    spaces.GetPowerBIWorkspace
2022-05-31T15:51:27.7987932Z ##[debug] 
2022-05-31T15:51:27.7995818Z ##[debug]Script stack trace:
2022-05-31T15:51:27.8009165Z ##[debug]at Get-PowerBIGroupPath, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.33\ps_modules\PowerBI\PowerBI.psm1: line 676
2022-05-31T15:51:27.8032515Z ##[debug]at Publish-PowerBIFile, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.33\ps_modules\PowerBI\PowerBI.psm1: line 766
2022-05-31T15:51:27.8034202Z ##[debug]at <ScriptBlock><Process>, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.33\run.ps1: line 112
2022-05-31T15:51:27.8047007Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-05-31T15:51:27.8059651Z ##[debug]at <ScriptBlock>, <No file>: line 22
2022-05-31T15:51:27.8073283Z ##[debug]at <ScriptBlock>, <No file>: line 18
2022-05-31T15:51:27.8086855Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-05-31T15:51:27.8098290Z ##[debug]Exception:
2022-05-31T15:51:27.8562871Z ##[debug]Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'Unauthorized'
2022-05-31T15:51:27.8575886Z ##[debug]   at Microsoft.PowerBI.Api.V2.Groups.<GetGroupsWithHttpMessagesAsync>d__5.MoveNext()
2022-05-31T15:51:27.8587394Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-05-31T15:51:27.8599068Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-05-31T15:51:27.8618990Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-05-31T15:51:27.8625882Z ##[debug]   at Microsoft.PowerBI.Api.V2.GroupsExtensions.<GetGroupsAsync>d__1.MoveNext()
2022-05-31T15:51:27.8638952Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-05-31T15:51:27.8655309Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-05-31T15:51:27.8668243Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-05-31T15:51:27.8682183Z ##[debug]   at Microsoft.PowerBI.Api.V2.GroupsExtensions.GetGroups(IGroups operations, String filter, Nullable`1 top, Nullable`1 skip)
2022-05-31T15:51:27.8704706Z ##[debug]   at Microsoft.PowerBI.Common.Api.Workspaces.WorkspacesClient.GetWorkspaces(String filter, Nullable`1 top, Nullable`1 skip)
2022-05-31T15:51:27.8707129Z ##[debug]   at Microsoft.PowerBI.Commands.Workspaces.GetPowerBIWorkspace.GetWorkspaces()
2022-05-31T15:51:27.8719699Z ##[debug]   at Microsoft.PowerBI.Commands.Workspaces.GetPowerBIWorkspace.ExecuteCmdlet()
2022-05-31T15:51:27.8737006Z ##[debug]   at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
2022-05-31T15:51:27.9001901Z ##[error]Operation returned an invalid status code 'Unauthorized'
2022-05-31T15:51:27.9012268Z ##[debug]Processed: ##vso[task.logissue type=error]Operation returned an invalid status code 'Unauthorized'
2022-05-31T15:51:27.9013480Z ##[debug]Request Uri: https://api.powerbi.com/v1.0/myorg/groups?$filter=tolower(name) eq 'hnltestworkspace'&$top=100
2022-05-31T15:51:27.9014287Z ##[debug]Status Code: Unauthorized (401)
2022-05-31T15:51:27.9018527Z ##[debug]3:51:27 PM - Get-PowerBIWorkspace end processing.
2022-05-31T15:51:28.1688155Z Done processing Power BI Actions
2022-05-31T15:51:28.2667173Z ##[debug]Caught exception from task script.
2022-05-31T15:51:28.2723250Z ##[debug]Error record:
2022-05-31T15:51:28.2893574Z ##[debug]Power BI Workspace: HNLTestWorkspace does not exist
2022-05-31T15:51:28.2907555Z ##[debug]At D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.33\ps_modules\PowerBI\PowerBI.psm1:682 char:13
2022-05-31T15:51:28.2920083Z ##[debug]+             Throw "Power BI Workspace: $WorkspaceName does not exist"
2022-05-31T15:51:28.2933038Z ##[debug]+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-05-31T15:51:28.2966461Z ##[debug]    + CategoryInfo          : OperationStopped: (Power BI Worksp... does not exist:String) [], RuntimeException
2022-05-31T15:51:28.2979892Z ##[debug]    + FullyQualifiedErrorId : Power BI Workspace: HNLTestWorkspace does not exist
2022-05-31T15:51:28.2987388Z ##[debug] 
2022-05-31T15:51:28.3003654Z ##[debug]Script stack trace:
2022-05-31T15:51:28.3022767Z ##[debug]at Get-PowerBIGroupPath, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.33\ps_modules\PowerBI\PowerBI.psm1: line 682
2022-05-31T15:51:28.3035492Z ##[debug]at Publish-PowerBIFile, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.33\ps_modules\PowerBI\PowerBI.psm1: line 766
2022-05-31T15:51:28.3048034Z ##[debug]at <ScriptBlock><Process>, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.33\run.ps1: line 112
2022-05-31T15:51:28.3060475Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-05-31T15:51:28.3072945Z ##[debug]at <ScriptBlock>, <No file>: line 22
2022-05-31T15:51:28.3089496Z ##[debug]at <ScriptBlock>, <No file>: line 18
2022-05-31T15:51:28.3101679Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-05-31T15:51:28.3120281Z ##[debug]Exception:
2022-05-31T15:51:28.3161256Z ##[debug]System.Management.Automation.RuntimeException: Power BI Workspace: HNLTestWorkspace does not exist
2022-05-31T15:51:28.3179665Z ##[error]Power BI Workspace: HNLTestWorkspace does not exist
2022-05-31T15:51:28.3181826Z ##[debug]Processed: ##vso[task.logissue type=error]Power BI Workspace: HNLTestWorkspace does not exist
2022-05-31T15:51:28.3197661Z ##[debug]Processed: ##vso[task.complete result=Failed]
2022-05-31T15:51:28.3636320Z ##[section]Finishing: PowerBIActions`

**Comment by yorickbouma** [comment]
This was solved by having the SPN added on the tenant level by our Global Admin.

**Comment by zhunipingan** [comment]
Hi @yorickbouma , I meet the same iuuse, but I cannot understand your solution, could you describe it clearer again, appreciate for your help!
