### ISSUE TITLE
PowerBIActions@5 -> UpdateSqlCreds -> ##[error]Cannot bind argument to parameter 'Name' because it is an empty string.

### ISSUE THREAD

**Issue by DanielEMoore** [maikvandergaag/msft-extensions#441]
**Describe the issue**
I am trying to update SQL DataSource Credentials and get an error with 'name' being empty

**Extension **
 - Extension: [Power Bi Actions]
 - Version: [5.4.39]

**To Reproduce**
1. Call task in azure devops yml file...
2.     - task: PowerBIActions@5
      inputs:
        Action: 'UpdateSqlCreds'
        WorkspaceName: 'Test'
        Scope: 'Organization'
        ReportName: 'Staff'
        Username: 'test-powerbi'
        Password: 'xxxxxxxxx'
3. Run job
4. Get error saying that 'name' is null

**Expected behavior**
I expect that the SQL creds be updated with the new ones.

**Log info**

`2022-09-20T15:18:33.3855376Z ##[debug]Evaluating condition for step: 'PowerBIActions'
2022-09-20T15:18:33.3857992Z ##[debug]Evaluating: SucceededNode()
2022-09-20T15:18:33.3858718Z ##[debug]Evaluating SucceededNode:
2022-09-20T15:18:33.3859754Z ##[debug]=> True
2022-09-20T15:18:33.3860227Z ##[debug]Result: True
2022-09-20T15:18:33.3860738Z ##[section]Starting: PowerBIActions
2022-09-20T15:18:33.3998991Z ==============================================================================
2022-09-20T15:18:33.3999463Z Task         : Power BI Actions
2022-09-20T15:18:33.3999775Z Description  : Release Task Power BI Actions
2022-09-20T15:18:33.3999992Z Version      : 5.4.39
2022-09-20T15:18:33.4000176Z Author       : Maik van der Gaag
2022-09-20T15:18:33.4000361Z Help         : 
2022-09-20T15:18:33.4000605Z ==============================================================================
2022-09-20T15:18:34.1312487Z ##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
2022-09-20T15:18:34.3216314Z Starting Power BI Actions extension
2022-09-20T15:18:34.3320789Z ##[debug]Entering C:\agent1v2\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.39\run.ps1.
2022-09-20T15:18:34.3374502Z ### Required Module is needed. Importing now...
2022-09-20T15:18:34.3412732Z ##[debug]Loading module from path 'C:\agent1v2\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.39\ps_modules\MicrosoftPowerBIMgmt.Profile\1.2.1077\MicrosoftPowerBIMgmt.Profile.psd1'.
2022-09-20T15:18:34.3611953Z ##[debug]Loading 'TypesToProcess' from path 'C:\agent1v2\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.39\ps_modules\MicrosoftPowerBIMgmt.Profile\1.2.1077\Microsoft.PowerBI.Commands.Profile.types.ps1xml'.
2022-09-20T15:18:34.3639766Z ##[debug]Loading 'FormatsToProcess' from path 'C:\agent1v2\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.39\ps_modules\MicrosoftPowerBIMgmt.Profile\1.2.1077\Microsoft.PowerBI.Commands.Profile.format.ps1xml'.
2022-09-20T15:18:34.3875009Z ##[debug]Populating RepositorySourceLocation property for module MicrosoftPowerBIMgmt.Profile.
2022-09-20T15:18:34.3903059Z ##[debug]Loading module from path 'C:\agent1v2\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.39\ps_modules\MicrosoftPowerBIMgmt.Profile\1.2.1077\.\lib\netstandard2.0\Microsoft.PowerBI.Commands.Profile.dll'.
2022-09-20T15:18:34.3990096Z ##[debug]Exporting cmdlet 'Connect-PowerBIServiceAccount'.
2022-09-20T15:18:34.4014628Z ##[debug]Exporting cmdlet 'Disconnect-PowerBIServiceAccount'.
2022-09-20T15:18:34.4043019Z ##[debug]Exporting cmdlet 'Get-PowerBIAccessToken'.
2022-09-20T15:18:34.4068202Z ##[debug]Exporting cmdlet 'Invoke-PowerBIRestMethod'.
2022-09-20T15:18:34.4089599Z ##[debug]Exporting cmdlet 'Resolve-PowerBIError'.
2022-09-20T15:18:34.4111737Z ##[debug]Importing cmdlet 'Connect-PowerBIServiceAccount'.
2022-09-20T15:18:34.4131592Z ##[debug]Importing cmdlet 'Disconnect-PowerBIServiceAccount'.
2022-09-20T15:18:34.4152738Z ##[debug]Importing cmdlet 'Get-PowerBIAccessToken'.
2022-09-20T15:18:34.4175588Z ##[debug]Importing cmdlet 'Invoke-PowerBIRestMethod'.
2022-09-20T15:18:34.4199207Z ##[debug]Importing cmdlet 'Resolve-PowerBIError'.
2022-09-20T15:18:34.4221466Z ##[debug]Importing alias 'Add-PowerBIServiceAccount'.
2022-09-20T15:18:34.4244139Z ##[debug]Importing alias 'Login-PowerBI'.
2022-09-20T15:18:34.4265281Z ##[debug]Importing alias 'Login-PowerBIServiceAccount'.
2022-09-20T15:18:34.4286191Z ##[debug]Importing alias 'Logout-PowerBI'.
2022-09-20T15:18:34.4306940Z ##[debug]Importing alias 'Logout-PowerBIServiceAccount'.
2022-09-20T15:18:34.4326741Z ##[debug]Importing alias 'Remove-PowerBIServiceAccount'.
2022-09-20T15:18:34.4349239Z ##[debug]Importing alias 'Set-PowerBIServiceAccount'.
2022-09-20T15:18:34.4385408Z ##[debug]Loading module from path 'C:\agent1v2\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.39\ps_modules\MicrosoftPowerBIMgmt.Workspaces\1.2.1077\MicrosoftPowerBIMgmt.Workspaces.psd1'.
2022-09-20T15:18:34.4592728Z ##[debug]Loading 'FormatsToProcess' from path 'C:\agent1v2\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.39\ps_modules\MicrosoftPowerBIMgmt.Workspaces\1.2.1077\Microsoft.PowerBI.Commands.Workspaces.format.ps1xml'.
2022-09-20T15:18:34.4774486Z ##[debug]Populating RepositorySourceLocation property for module MicrosoftPowerBIMgmt.Workspaces.
2022-09-20T15:18:34.4805824Z ##[debug]Loading module from path 'C:\agent1v2\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.39\ps_modules\MicrosoftPowerBIMgmt.Workspaces\1.2.1077\.\lib\netstandard2.0\Microsoft.PowerBI.Commands.Workspaces.dll'.
2022-09-20T15:18:34.4881447Z ##[debug]Exporting cmdlet 'Add-PowerBIWorkspaceUser'.
2022-09-20T15:18:34.4903028Z ##[debug]Exporting cmdlet 'Get-PowerBIWorkspace'.
2022-09-20T15:18:34.4925376Z ##[debug]Exporting cmdlet 'Get-PowerBIWorkspaceMigrationStatus'.
2022-09-20T15:18:34.4948974Z ##[debug]Exporting cmdlet 'New-PowerBIWorkspace'.
2022-09-20T15:18:34.5489202Z ##[debug]Exporting cmdlet 'Remove-PowerBIWorkspaceUser'.
2022-09-20T15:18:34.5514879Z ##[debug]Exporting cmdlet 'Restore-PowerBIWorkspace'.
2022-09-20T15:18:34.5540492Z ##[debug]Exporting cmdlet 'Set-PowerBIWorkspace'.
2022-09-20T15:18:34.5565797Z ##[debug]Importing cmdlet 'Add-PowerBIWorkspaceUser'.
2022-09-20T15:18:34.5591130Z ##[debug]Importing cmdlet 'Get-PowerBIWorkspace'.
2022-09-20T15:18:34.5619121Z ##[debug]Importing cmdlet 'Get-PowerBIWorkspaceMigrationStatus'.
2022-09-20T15:18:34.5640472Z ##[debug]Importing cmdlet 'New-PowerBIWorkspace'.
2022-09-20T15:18:34.5663181Z ##[debug]Importing cmdlet 'Remove-PowerBIWorkspaceUser'.
2022-09-20T15:18:34.5685029Z ##[debug]Importing cmdlet 'Restore-PowerBIWorkspace'.
2022-09-20T15:18:34.5711096Z ##[debug]Importing cmdlet 'Set-PowerBIWorkspace'.
2022-09-20T15:18:34.5730993Z ##[debug]Importing alias 'Add-PowerBIGroupUser'.
2022-09-20T15:18:34.5748940Z ##[debug]Importing alias 'Get-PowerBIGroup'.
2022-09-20T15:18:34.5767627Z ##[debug]Importing alias 'Get-PowerBIGroupMigrationStatus'.
2022-09-20T15:18:34.5788190Z ##[debug]Importing alias 'New-PowerBIGroup'.
2022-09-20T15:18:34.5805366Z ##[debug]Importing alias 'Remove-PowerBIGroupUser'.
2022-09-20T15:18:34.5823990Z ##[debug]Importing alias 'Restore-PowerBIGroup'.
2022-09-20T15:18:34.5843208Z ##[debug]Importing alias 'Set-PowerBIGroup'.
2022-09-20T15:18:34.5879019Z ##[debug]Loading module from path 'C:\agent1v2\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.39\ps_modules\MicrosoftPowerBIMgmt.Reports\1.2.1077\MicrosoftPowerBIMgmt.Reports.psd1'.
2022-09-20T15:18:34.6074338Z ##[debug]Populating RepositorySourceLocation property for module MicrosoftPowerBIMgmt.Reports.
2022-09-20T15:18:34.6110121Z ##[debug]Loading module from path 'C:\agent1v2\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.39\ps_modules\MicrosoftPowerBIMgmt.Reports\1.2.1077\.\lib\netstandard2.0\Microsoft.PowerBI.Commands.Reports.dll'.
2022-09-20T15:18:34.6165515Z ##[debug]Exporting cmdlet 'Copy-PowerBIReport'.
2022-09-20T15:18:34.6186079Z ##[debug]Exporting cmdlet 'Copy-PowerBITile'.
2022-09-20T15:18:34.6205746Z ##[debug]Exporting cmdlet 'Export-PowerBIReport'.
2022-09-20T15:18:34.6226850Z ##[debug]Exporting cmdlet 'Get-PowerBIDashboard'.
2022-09-20T15:18:34.6247841Z ##[debug]Exporting cmdlet 'Get-PowerBIImport'.
2022-09-20T15:18:34.6268751Z ##[debug]Exporting cmdlet 'Get-PowerBIReport'.
2022-09-20T15:18:34.6288093Z ##[debug]Exporting cmdlet 'Get-PowerBITile'.
2022-09-20T15:18:34.6310601Z ##[debug]Exporting cmdlet 'New-PowerBIDashboard'.
2022-09-20T15:18:34.6329752Z ##[debug]Exporting cmdlet 'New-PowerBIReport'.
2022-09-20T15:18:34.6351085Z ##[debug]Exporting cmdlet 'Remove-PowerBIReport'.
2022-09-20T15:18:34.6370744Z ##[debug]Importing cmdlet 'Copy-PowerBIReport'.
2022-09-20T15:18:34.6390977Z ##[debug]Importing cmdlet 'Copy-PowerBITile'.
2022-09-20T15:18:34.6410270Z ##[debug]Importing cmdlet 'Export-PowerBIReport'.
2022-09-20T15:18:34.6430127Z ##[debug]Importing cmdlet 'Get-PowerBIDashboard'.
2022-09-20T15:18:34.6449329Z ##[debug]Importing cmdlet 'Get-PowerBIImport'.
2022-09-20T15:18:34.6471940Z ##[debug]Importing cmdlet 'Get-PowerBIReport'.
2022-09-20T15:18:34.6491361Z ##[debug]Importing cmdlet 'Get-PowerBITile'.
2022-09-20T15:18:34.6515918Z ##[debug]Importing cmdlet 'New-PowerBIDashboard'.
2022-09-20T15:18:34.6538703Z ##[debug]Importing cmdlet 'New-PowerBIReport'.
2022-09-20T15:18:34.6562049Z ##[debug]Importing cmdlet 'Remove-PowerBIReport'.
2022-09-20T15:18:34.6586133Z ##[debug]Importing alias 'Get-PowerBIDashboardTile'.
2022-09-20T15:18:34.6635403Z ##[debug]Loading module from path 'C:\agent1v2\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.39\ps_modules\MicrosoftPowerBIMgmt.Data\1.2.1077\MicrosoftPowerBIMgmt.Data.psd1'.
2022-09-20T15:18:34.6830906Z ##[debug]Loading 'FormatsToProcess' from path 'C:\agent1v2\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.39\ps_modules\MicrosoftPowerBIMgmt.Data\1.2.1077\Microsoft.PowerBI.Commands.Data.format.ps1xml'.
2022-09-20T15:18:34.7091798Z ##[debug]Populating RepositorySourceLocation property for module MicrosoftPowerBIMgmt.Data.
2022-09-20T15:18:34.7121314Z ##[debug]Loading module from path 'C:\agent1v2\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.39\ps_modules\MicrosoftPowerBIMgmt.Data\1.2.1077\.\lib\netstandard2.0\Microsoft.PowerBI.Commands.Data.dll'.
2022-09-20T15:18:34.7176966Z ##[debug]Exporting cmdlet 'Add-PowerBIDataset'.
2022-09-20T15:18:34.7198318Z ##[debug]Exporting cmdlet 'Add-PowerBIRow'.
2022-09-20T15:18:34.7218468Z ##[debug]Exporting cmdlet 'Export-PowerBIDataflow'.
2022-09-20T15:18:34.7238666Z ##[debug]Exporting cmdlet 'Get-PowerBIDataflow'.
2022-09-20T15:18:34.7261049Z ##[debug]Exporting cmdlet 'Get-PowerBIDataflowDatasource'.
2022-09-20T15:18:34.7283573Z ##[debug]Exporting cmdlet 'Get-PowerBIDataset'.
2022-09-20T15:18:34.7303236Z ##[debug]Exporting cmdlet 'Get-PowerBIDatasource'.
2022-09-20T15:18:34.7322936Z ##[debug]Exporting cmdlet 'Get-PowerBITable'.
2022-09-20T15:18:34.7342777Z ##[debug]Exporting cmdlet 'New-PowerBIColumn'.
2022-09-20T15:18:34.7363399Z ##[debug]Exporting cmdlet 'New-PowerBIDataset'.
2022-09-20T15:18:34.7382944Z ##[debug]Exporting cmdlet 'New-PowerBITable'.
2022-09-20T15:18:34.7403135Z ##[debug]Exporting cmdlet 'Remove-PowerBIRow'.
2022-09-20T15:18:34.7426049Z ##[debug]Exporting cmdlet 'Set-PowerBIDataset'.
2022-09-20T15:18:34.7446755Z ##[debug]Exporting cmdlet 'Set-PowerBITable'.
2022-09-20T15:18:34.7467189Z ##[debug]Importing cmdlet 'Add-PowerBIDataset'.
2022-09-20T15:18:34.7487744Z ##[debug]Importing cmdlet 'Add-PowerBIRow'.
2022-09-20T15:18:34.7507935Z ##[debug]Importing cmdlet 'Export-PowerBIDataflow'.
2022-09-20T15:18:34.7528939Z ##[debug]Importing cmdlet 'Get-PowerBIDataflow'.
2022-09-20T15:18:34.7548367Z ##[debug]Importing cmdlet 'Get-PowerBIDataflowDatasource'.
2022-09-20T15:18:34.7568876Z ##[debug]Importing cmdlet 'Get-PowerBIDataset'.
2022-09-20T15:18:34.7591475Z ##[debug]Importing cmdlet 'Get-PowerBIDatasource'.
2022-09-20T15:18:34.7611800Z ##[debug]Importing cmdlet 'Get-PowerBITable'.
2022-09-20T15:18:34.7631963Z ##[debug]Importing cmdlet 'New-PowerBIColumn'.
2022-09-20T15:18:34.7651633Z ##[debug]Importing cmdlet 'New-PowerBIDataset'.
2022-09-20T15:18:34.7672872Z ##[debug]Importing cmdlet 'New-PowerBITable'.
2022-09-20T15:18:34.7692570Z ##[debug]Importing cmdlet 'Remove-PowerBIRow'.
2022-09-20T15:18:34.7713174Z ##[debug]Importing cmdlet 'Set-PowerBIDataset'.
2022-09-20T15:18:34.7733355Z ##[debug]Importing cmdlet 'Set-PowerBITable'.
2022-09-20T15:18:34.7744618Z ### Trying to import the incorporated module for PowerBI
2022-09-20T15:18:34.7771328Z ##[debug]Loading module from path 'C:\agent1v2\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.39\ps_modules\PowerBI\PowerBI.psm1'.
2022-09-20T15:18:34.9175281Z ##[debug]Exporting function 'Set-PowerBIDatasetToGatewayInGroup'.
2022-09-20T15:18:34.9202395Z ##[debug]Exporting function 'Get-PowerBIDatasetGatewayDatasourceInGroup'.
2022-09-20T15:18:34.9223021Z ##[debug]Exporting function 'Update-PowerBIDatasetSource'.
2022-09-20T15:18:34.9251058Z ##[debug]Exporting function 'Update-PowerBIDatasetDatasourcesInGroup'.
2022-09-20T15:18:34.9271206Z ##[debug]Exporting function 'Get-PowerBIDataSourcesInGateway'.
2022-09-20T15:18:34.9291595Z ##[debug]Exporting function 'Get-PowerBIGateways'.
2022-09-20T15:18:34.9311554Z ##[debug]Exporting function 'Set-DatasetOwnership'.
2022-09-20T15:18:34.9339002Z ##[debug]Exporting function 'Set-PowerBIDataSetOwnership'.
2022-09-20T15:18:34.9359280Z ##[debug]Exporting function 'Update-PowerBIDatasetParameter'.
2022-09-20T15:18:34.9386560Z ##[debug]Exporting function 'Update-PowerBIDatasetParameters'.
2022-09-20T15:18:34.9406631Z ##[debug]Exporting function 'Invoke-API'.
2022-09-20T15:18:34.9434479Z ##[debug]Exporting function 'New-DataSetSingleRefresh'.
2022-09-20T15:18:34.9454667Z ##[debug]Exporting function 'New-DatasetRefresh'.
2022-09-20T15:18:34.9475114Z ##[debug]Exporting function 'Update-PowerBIDatasetDatasources'.
2022-09-20T15:18:34.9495847Z ##[debug]Exporting function 'Update-PowerBIDatasetDatasource'.
2022-09-20T15:18:34.9523334Z ##[debug]Exporting function 'Update-ConnectionStringDirectQuery'.
2022-09-20T15:18:34.9545016Z ##[debug]Exporting function 'Get-PowerBIReport'.
2022-09-20T15:18:34.9564483Z ##[debug]Exporting function 'Get-PowerBiDataSet'.
2022-09-20T15:18:34.9755061Z ##[debug]Exporting function 'Get-PowerBiDataSetDataSources'.
2022-09-20T15:18:34.9772133Z ##[debug]Exporting function 'Get-PowerBiDataSets'.
2022-09-20T15:18:34.9790708Z ##[debug]Exporting function 'Get-PowerBiParameters'.
2022-09-20T15:18:34.9808240Z ##[debug]Exporting function 'New-PowerBIWorkSpace'.
2022-09-20T15:18:34.9825464Z ##[debug]Exporting function 'Remove-PowerBIWorkSpace'.
2022-09-20T15:18:34.9843455Z ##[debug]Exporting function 'Import-PowerBIFile'.
2022-09-20T15:18:34.9860704Z ##[debug]Exporting function 'Get-PowerBIGroupPath'.
2022-09-20T15:18:34.9877758Z ##[debug]Exporting function 'Add-PowerBIWorkspaceUsers'.
2022-09-20T15:18:34.9895818Z ##[debug]Exporting function 'Add-PowerBIWorkspaceGroup'.
2022-09-20T15:18:34.9915744Z ##[debug]Exporting function 'Add-PowerBIWorkspaceSP'.
2022-09-20T15:18:34.9932897Z ##[debug]Exporting function 'Publish-PowerBIFile'.
2022-09-20T15:18:34.9951355Z ##[debug]Exporting function 'Publish-PowerBIFileApi'.
2022-09-20T15:18:34.9969452Z ##[debug]Exporting function 'Remove-PowerBIReport'.
2022-09-20T15:18:34.9987061Z ##[debug]Exporting function 'Get-PowerBICapacity'.
2022-09-20T15:18:35.0005649Z ##[debug]Exporting function 'Set-Capacity'.
2022-09-20T15:18:35.0022756Z ##[debug]Exporting function 'Redo-PowerBIReport'.
2022-09-20T15:18:35.0040532Z ##[debug]Exporting function 'Redo-PowerBIReportCrossWorkspace'.
2022-09-20T15:18:35.0060189Z ##[debug]Exporting function 'Update-BasicSQLDataSourceCredentials'.
2022-09-20T15:18:35.0077355Z ##[debug]Exporting function 'Set-RefreshSchedule'.
2022-09-20T15:18:35.0096045Z ##[debug]Exporting function 'Publish-TabularEditor'.
2022-09-20T15:18:35.0113978Z ##[debug]Exporting function 'Add-PowerBIDatasetPermissions'.
2022-09-20T15:18:35.0131366Z ##[debug]Exporting function 'Get-PowerBiDatasetUsers'.
2022-09-20T15:18:35.0153513Z ##[debug]Importing function 'Add-PowerBIDatasetPermissions'.
2022-09-20T15:18:35.0170571Z ##[debug]Importing function 'Add-PowerBIWorkspaceGroup'.
2022-09-20T15:18:35.0188622Z ##[debug]Importing function 'Add-PowerBIWorkspaceSP'.
2022-09-20T15:18:35.0206517Z ##[debug]Importing function 'Add-PowerBIWorkspaceUsers'.
2022-09-20T15:18:35.0223505Z ##[debug]Importing function 'Get-PowerBICapacity'.
2022-09-20T15:18:35.0241758Z ##[debug]Importing function 'Get-PowerBiDataSet'.
2022-09-20T15:18:35.0260067Z ##[debug]Importing function 'Get-PowerBiDataSetDataSources'.
2022-09-20T15:18:35.0277041Z ##[debug]Importing function 'Get-PowerBIDatasetGatewayDatasourceInGroup'.
2022-09-20T15:18:35.0297337Z ##[debug]Importing function 'Get-PowerBiDataSets'.
2022-09-20T15:18:35.0314490Z ##[debug]Importing function 'Get-PowerBiDatasetUsers'.
2022-09-20T15:18:35.0332547Z ##[debug]Importing function 'Get-PowerBIDataSourcesInGateway'.
2022-09-20T15:18:35.0350362Z ##[debug]Importing function 'Get-PowerBIGateways'.
2022-09-20T15:18:35.0367234Z ##[debug]Importing function 'Get-PowerBIGroupPath'.
2022-09-20T15:18:35.0385394Z ##[debug]Importing function 'Get-PowerBiParameters'.
2022-09-20T15:18:35.0403350Z ##[debug]Importing function 'Get-PowerBIReport'.
2022-09-20T15:18:35.0420583Z ##[debug]Importing function 'Import-PowerBIFile'.
2022-09-20T15:18:35.0441135Z ##[debug]Importing function 'Invoke-API'.
2022-09-20T15:18:35.0458306Z ##[debug]Importing function 'New-DatasetRefresh'.
2022-09-20T15:18:35.0476553Z ##[debug]Importing function 'New-DataSetSingleRefresh'.
2022-09-20T15:18:35.0494218Z ##[debug]Importing function 'New-PowerBIWorkSpace'.
2022-09-20T15:18:35.0511090Z ##[debug]Importing function 'Publish-PowerBIFile'.
2022-09-20T15:18:35.0529305Z ##[debug]Importing function 'Publish-PowerBIFileApi'.
2022-09-20T15:18:35.0546387Z ##[debug]Importing function 'Publish-TabularEditor'.
2022-09-20T15:18:35.0564661Z ##[debug]Importing function 'Redo-PowerBIReport'.
2022-09-20T15:18:35.0584821Z ##[debug]Importing function 'Redo-PowerBIReportCrossWorkspace'.
2022-09-20T15:18:35.0601873Z ##[debug]Importing function 'Remove-PowerBIReport'.
2022-09-20T15:18:35.0620213Z ##[debug]Importing function 'Remove-PowerBIWorkSpace'.
2022-09-20T15:18:35.0637780Z ##[debug]Importing function 'Set-Capacity'.
2022-09-20T15:18:35.0655023Z ##[debug]Importing function 'Set-DatasetOwnership'.
2022-09-20T15:18:35.0673120Z ##[debug]Importing function 'Set-PowerBIDataSetOwnership'.
2022-09-20T15:18:35.0690177Z ##[debug]Importing function 'Set-PowerBIDatasetToGatewayInGroup'.
2022-09-20T15:18:35.0707711Z ##[debug]Importing function 'Set-RefreshSchedule'.
2022-09-20T15:18:35.0727727Z ##[debug]Importing function 'Update-BasicSQLDataSourceCredentials'.
2022-09-20T15:18:35.0744709Z ##[debug]Importing function 'Update-ConnectionStringDirectQuery'.
2022-09-20T15:18:35.0762850Z ##[debug]Importing function 'Update-PowerBIDatasetDatasource'.
2022-09-20T15:18:35.0780467Z ##[debug]Importing function 'Update-PowerBIDatasetDatasources'.
2022-09-20T15:18:35.0797773Z ##[debug]Importing function 'Update-PowerBIDatasetDatasourcesInGroup'.
2022-09-20T15:18:35.0816199Z ##[debug]Importing function 'Update-PowerBIDatasetParameter'.
2022-09-20T15:18:35.0834046Z ##[debug]Importing function 'Update-PowerBIDatasetParameters'.
2022-09-20T15:18:35.0851169Z ##[debug]Importing function 'Update-PowerBIDatasetSource'.
2022-09-20T15:18:35.1097263Z ##[debug]INPUT_POWERBISERVICEENDPOINT (empty)
2022-09-20T15:18:35.1342176Z Done processing Power BI Actions
2022-09-20T15:18:35.1440701Z ##[debug]Caught exception from task script.
2022-09-20T15:18:35.1475345Z ##[debug]Error record:
2022-09-20T15:18:35.2385440Z ##[debug]C:\agent1v2\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.39\run.ps1 : Cannot bind argument to parameter 'Name' because it is an empty string.
2022-09-20T15:18:35.2397279Z ##[debug]At line:1 char:1
2022-09-20T15:18:35.2413913Z ##[debug]+ . 'C:\agent1v2\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0d ...
2022-09-20T15:18:35.2426504Z ##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-09-20T15:18:35.2453830Z ##[debug]    + CategoryInfo          : InvalidData: (:) [run.ps1], ParameterBindingValidationException
2022-09-20T15:18:35.2459586Z ##[debug]    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,run.ps1
2022-09-20T15:18:35.2818692Z ##[debug] 
2022-09-20T15:18:35.2846646Z ##[debug]Script stack trace:
2022-09-20T15:18:35.2886557Z ##[debug]at <ScriptBlock><Process>, C:\agent1v2\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.39\run.ps1: line 28
2022-09-20T15:18:35.2898292Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-09-20T15:18:35.2913586Z ##[debug]at <ScriptBlock>, <No file>: line 22
2022-09-20T15:18:35.2928292Z ##[debug]at <ScriptBlock>, <No file>: line 18
2022-09-20T15:18:35.2942214Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-09-20T15:18:35.2970658Z ##[debug]Exception:
2022-09-20T15:18:35.3023072Z ##[debug]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Name' because it is an empty string.
2022-09-20T15:18:35.3037533Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2022-09-20T15:18:35.3051536Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2022-09-20T15:18:35.3063795Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2022-09-20T15:18:35.3078843Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2022-09-20T15:18:35.3093674Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2022-09-20T15:18:35.3107365Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2022-09-20T15:18:35.3119635Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2022-09-20T15:18:35.3135628Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
2022-09-20T15:18:35.3150215Z ##[debug]   at System.Management.Automation.CommandProcessor.ProcessRecord()
2022-09-20T15:18:35.3373276Z ##[error]Cannot bind argument to parameter 'Name' because it is an empty string.
2022-09-20T15:18:35.3380569Z ##[debug]Processed: ##vso[task.logissue type=error]Cannot bind argument to parameter 'Name' because it is an empty string.
2022-09-20T15:18:35.3382659Z ##[debug]Processed: ##vso[task.complete result=Failed]
2022-09-20T15:18:35.3545387Z ##[section]Finishing: PowerBIActions`

**Comment by DanielEMoore** [comment]
Issue was i was missing the "PowerBIServiceEndpoint:" on my yml call. Your extension is great but its hard to work with some times in yml. Pipelines because you work in the dark. 

```
$serviceEndpoint = Get-VstsEndpoint -Name (Get-VstsInput -Name "PowerBIServiceEndpoint") -Require
		$verboseVariable = ConvertTo-Json -InputObject $serviceEndpoint
		Write-Verbose "$($verboseVariable)"
```

**Comment by maikvandergaag** [comment]
Yes I know. Will try to find some time to write some tutorials.
