### ISSUE TITLE
release variable json feauture : how is it used?

### ISSUE THREAD

**Issue by bahadir-be** [maikvandergaag/msft-extensions#481]
**For which extension would you like to add a feature request?**
Trigger Azure DevOps Pipeline

**Question**
release variable json feauture : how is it used?

First of all, thank you very much for this extension!

i got below error message :
![image](https://user-images.githubusercontent.com/62173919/232498189-38fbe507-1eb2-4651-b325-c13a7762a67d.png)

I using ***CustomerCode** variable on my Main pipeline ex:
![image](https://user-images.githubusercontent.com/62173919/232498564-6113f071-ad03-4bfb-b2af-949a42407c8e.png)

The same value is available in the pipeline to be triggered. ex:
![image](https://user-images.githubusercontent.com/62173919/232498784-efc19175-85cf-4a54-873a-f7a68bf3f5be.png)
The same value is present in the pipeline to be triggered.

The parameter I use is as follows.
{'*CustomerCode' : '$(*CustomerCode)','*CustomerCode' : '$(*CustomerCode)'}

Where am I doing wrong?

**Comment by maikvandergaag** [comment]
Could you maybe share a debug log file?

**Comment by bahadir-be** [comment]
> Could you maybe share a debug log file?

Yes sure
`2023-05-10T14:24:18.8519169Z ##[debug]Evaluating condition for step: 'Trigger Azure DevOps Pipeline: Release'
2023-05-10T14:24:18.8519854Z ##[debug]Evaluating: succeeded()
2023-05-10T14:24:18.8520084Z ##[debug]Evaluating succeeded:
2023-05-10T14:24:18.8520452Z ##[debug]=> True
2023-05-10T14:24:18.8520712Z ##[debug]Result: True
2023-05-10T14:24:18.8520992Z ##[section]Starting: Trigger Azure DevOps Pipeline: Release
2023-05-10T14:24:18.8630775Z ==============================================================================
2023-05-10T14:24:18.8630931Z Task         : Trigger Azure DevOps Pipeline
2023-05-10T14:24:18.8631047Z Description  : Build and Release Management task to trigger a Azure DevOps release or build pipeline.
2023-05-10T14:24:18.8631211Z Version      : 2.0.6
2023-05-10T14:24:18.8631382Z Author       : Maik van der Gaag
2023-05-10T14:24:18.8632247Z Help         : 
2023-05-10T14:24:18.8632323Z ==============================================================================
2023-05-10T14:24:19.8612457Z ##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
2023-05-10T14:24:19.8612996Z ##[debug]Entering D:\a\_tasks\TriggerPipeline_05485ce0-4948-481c-a89f-f21fa2fe9a74\2.0.6\run.ps1.
2023-05-10T14:24:19.8613425Z ##[debug]INPUT_CONNECTEDSERVICENAME: 'bc232695-a135-485f-a801-d303edfa8f18'
2023-05-10T14:24:19.8684307Z ##[debug]ENDPOINT_URL_bc232695-a135-485f-a801-d303edfa8f18: 'https://dev.azure.com/xxxclouddevops'
2023-05-10T14:24:19.8761984Z ##[debug]ENDPOINT_AUTH_bc232695-a135-485f-a801-d303edfa8f18: '********'
2023-05-10T14:24:19.8762772Z ##[debug]ENDPOINT_DATA_bc232695-a135-485f-a801-d303edfa8f18: '{"releaseUrl":"https://vsrm.dev.azure.com/xxxclouddevops"}'
2023-05-10T14:24:19.8832317Z ##[debug]INPUT_PROJECT: '0721a0d7-3c58-4e4a-b531-8c17145fbe51'
2023-05-10T14:24:19.8852960Z ##[debug]INPUT_BUILDDEFINITION (empty)
2023-05-10T14:24:19.8933380Z ##[debug]INPUT_RELEASEDEFINITION: '2'
2023-05-10T14:24:19.8934166Z ##[debug]INPUT_PIPELINE: 'Release'
2023-05-10T14:24:19.8942050Z ##[debug]INPUT_DESCRIPTION (empty)
2023-05-10T14:24:19.8962355Z ##[debug]INPUT_BRANCH (empty)
2023-05-10T14:24:19.8982411Z ##[debug]INPUT_BUILDNUMBER (empty)
2023-05-10T14:24:19.9002029Z ##[debug]INPUT_STAGES (empty)
2023-05-10T14:24:19.9021735Z ##[debug]INPUT_BUILDAPIVERSION: '6.0'
2023-05-10T14:24:19.9041053Z ##[debug]INPUT_RELEASEAPIVERSION: '6.0'
2023-05-10T14:24:19.9060708Z ##[debug]INPUT_VARIABLEINPUT: '{'*CustomerCode' : 'C062','*CustomerCode' : 'C062'}'
2023-05-10T14:24:19.9068201Z ******************************
2023-05-10T14:24:19.9075200Z ** Service Connection: bc232695-a135-485f-a801-d303edfa8f18
2023-05-10T14:24:19.9081264Z ** Release Url: https://vsrm.dev.azure.com/xxxclouddevops
2023-05-10T14:24:19.9087806Z ** Organization Url: https://dev.azure.com/xxxclouddevops
2023-05-10T14:24:19.9094564Z ** Token: ***
2023-05-10T14:24:19.9100910Z ** Project name: 0721a0d7-3c58-4e4a-b531-8c17145fbe51
2023-05-10T14:24:19.9107052Z ** Pipeline: Release
2023-05-10T14:24:19.9113495Z ** Build pipeline: 
2023-05-10T14:24:19.9119848Z ** Release pipeline: 2
2023-05-10T14:24:19.9126374Z ** Description: 
2023-05-10T14:24:19.9132649Z ** Branch: 
2023-05-10T14:24:19.9139100Z ** BuildNumber: 
2023-05-10T14:24:19.9145394Z ** Stages: 
2023-05-10T14:24:19.9151785Z ** Build Api Version: 6.0
2023-05-10T14:24:19.9157976Z ** Release Api Version: 6.0
2023-05-10T14:24:19.9163922Z ******************************
2023-05-10T14:24:20.1149950Z ##[debug]GET https://vsrm.dev.azure.com/xxxclouddevops/0721a0d7-3c58-4e4a-b531-8c17145fbe51/_apis/release/definitions/2 with 0-byte payload
2023-05-10T14:24:20.4249811Z ##[debug]received 16266-byte response of content type application/json; charset=utf-8; api-version=7.0
2023-05-10T14:24:20.4481740Z ##[debug]GET https://vsrm.dev.azure.com/xxxclouddevops/0721a0d7-3c58-4e4a-b531-8c17145fbe51/_apis/Release/definitions/2 with 0-byte payload
2023-05-10T14:24:20.7969492Z ##[debug]received 16266-byte response of content type application/json; charset=utf-8; api-version=7.0
2023-05-10T14:24:20.9561536Z ##[debug]Leaving D:\a\_tasks\TriggerPipeline_05485ce0-4948-481c-a89f-f21fa2fe9a74\2.0.6\run.ps1.
2023-05-10T14:24:21.0715976Z ##[debug]Caught exception from task script.
2023-05-10T14:24:21.0744574Z ##[debug]Error record:
2023-05-10T14:24:21.1246030Z ##[debug]D:\a\_tasks\TriggerPipeline_05485ce0-4948-481c-a89f-f21fa2fe9a74\2.0.6\run-release.ps1 : parsing "*CustomerCode" - Quantifier {x,y} following nothing.
2023-05-10T14:24:21.1258142Z ##[debug]At D:\a\_tasks\TriggerPipeline_05485ce0-4948-481c-a89f-f21fa2fe9a74\2.0.6\run.ps1:59 char:3
2023-05-10T14:24:21.1269228Z ##[debug]+         .\run-release.ps1 -OrganizationUrl $organizationUrl -ReleaseU ...
2023-05-10T14:24:21.1280737Z ##[debug]+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-05-10T14:24:21.1291737Z ##[debug]    + CategoryInfo          : OperationStopped: (:) [run-release.ps1], ArgumentException
2023-05-10T14:24:21.1302742Z ##[debug]    + FullyQualifiedErrorId : System.ArgumentException,run-release.ps1
2023-05-10T14:24:21.1313562Z ##[debug] 
2023-05-10T14:24:21.1330599Z ##[debug]Script stack trace:
2023-05-10T14:24:21.2320104Z ##[debug]at <ScriptBlock>, D:\a\_tasks\TriggerPipeline_05485ce0-4948-481c-a89f-f21fa2fe9a74\2.0.6\run-release.ps1: line 92
2023-05-10T14:24:21.2332081Z ##[debug]at <ScriptBlock>, D:\a\_tasks\TriggerPipeline_05485ce0-4948-481c-a89f-f21fa2fe9a74\2.0.6\run.ps1: line 59
2023-05-10T14:24:21.2342862Z ##[debug]at <ScriptBlock>, <No file>: line 1
2023-05-10T14:24:21.2353223Z ##[debug]at <ScriptBlock>, <No file>: line 22
2023-05-10T14:24:21.2364265Z ##[debug]at <ScriptBlock>, <No file>: line 18
2023-05-10T14:24:21.2380192Z ##[debug]at <ScriptBlock>, <No file>: line 1
2023-05-10T14:24:21.2417145Z ##[debug]Exception:
2023-05-10T14:24:21.2426856Z ##[debug]System.ArgumentException: parsing "*CustomerCode" - Quantifier {x,y} following nothing.
2023-05-10T14:24:21.2436252Z ##[debug]   at System.Text.RegularExpressions.RegexParser.ScanRegex()
2023-05-10T14:24:21.2445445Z ##[debug]   at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
2023-05-10T14:24:21.2454683Z ##[debug]   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
2023-05-10T14:24:21.2464463Z ##[debug]   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options)
2023-05-10T14:24:21.2474048Z ##[debug]   at System.Management.Automation.ParserOps.NewRegex(String patternString, RegexOptions options)
2023-05-10T14:24:21.2483500Z ##[debug]   at System.Management.Automation.ParserOps.MatchOperator(ExecutionContext context, IScriptExtent errorPosition, Object lval, Object rval, Boolean notMatch, Boolean ignoreCase)
2023-05-10T14:24:21.2493430Z ##[debug]   at System.Management.Automation.Interpreter.FuncCallInstruction`7.Run(InterpretedFrame frame)
2023-05-10T14:24:21.2536872Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2023-05-10T14:24:21.2712356Z ##[error]parsing "*CustomerCode" - Quantifier {x,y} following nothing.
2023-05-10T14:24:21.2721118Z ##[debug]Processed: ##vso[task.logissue type=error]parsing "*CustomerCode" - Quantifier {x,y} following nothing.
2023-05-10T14:24:21.2722279Z ##[debug]Processed: ##vso[task.complete result=Failed]
2023-05-10T14:24:21.2915980Z ##[section]Finishing: Trigger Azure DevOps Pipeline: Release
`

**Comment by maikvandergaag** [comment]
Have you tried it without the * prefix?

**Comment by bahadir-be** [comment]
> Have you tried it without the * prefix?

@maikvandergaag solved after delete * prefix.
Any way use with this special character?

**Comment by maikvandergaag** [comment]
Have to check
